import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const port=47000+Math.floor(Math.random()*1000);const base=`http://127.0.0.1:${port}`;const temp=await fs.mkdtemp(path.join(os.tmpdir(),'qrajn84-'));const dbFile=path.join(temp,'db.json');let child;
const ua={'user-agent':'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/149 Mobile Safari/537.36'};

before(async()=>{child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',PUBLIC_ORIGIN:base,QR_AJN_DATA_FILE:dbFile},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',d=>stderr+=d);for(let i=0;i<80;i++){try{const r=await fetch(`${base}/api/v1/health`);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw new Error(`server did not start: ${stderr}`);});
after(async()=>{if(child&&!child.killed)child.kill();await fs.rm(temp,{recursive:true,force:true});});

async function j(url,opts={}){const r=await fetch(base+url,opts);let data={};try{data=await r.json();}catch{}return {r,data};}
async function createProfile(slug='ajn-test'){const {r,data}=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json',...ua},body:JSON.stringify({slug,name:'Sample Business',category:'Professional Services',tagline:'Professional public profile',about:'Public profile description',phone:'+10000000000',whatsapp:'10000000000',email:'hello@example.com',website:'https://example.com',address:'Business address',mapsUrl:'https://maps.google.com/',workingHours:'Mon-Sat',social:{instagram:'https://instagram.com/example'},customLinks:[{label:'Portfolio',url:'https://example.com/work'}],appearance:{template:'professional',accent:'ocean'}})});assert.equal(r.status,201);return data;}

test('health reports simplified profile analytics edition',async()=>{const {r,data}=await j('/api/v1/health');assert.equal(r.status,200);assert.equal(data.ok,true);assert.equal(data.version,'8.4.0');assert.equal(data.auth,'removed');assert.equal(data.billing,'removed');});

test('trackable QR uses a branded qrajn.online link with live availability',async()=>{let x=await j('/api/links/brand-live/availability');assert.equal(x.r.status,200);assert.equal(x.data.available,true);const created=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brandSlug:'brand-live',destinationUrl:'https://example.com/live'})});assert.equal(created.r.status,201);assert.equal(created.data.qr.brandSlug,'brand-live');assert.equal(created.data.redirectUrl,`${base}/brand-live`);assert.match(created.data.legacyRedirectUrl,/\/r\//);x=await j('/api/links/brand-live/availability');assert.equal(x.data.available,false);const r=await fetch(`${base}/brand-live`,{headers:ua,redirect:'manual'});assert.equal(r.status,302);assert.equal(r.headers.get('location'),'https://example.com/live');x=await j(`/api/manage/qrs/${created.data.qr.id}`,{headers:{'x-manage-token':created.data.manageToken}});assert.equal(x.r.status,200);assert.equal(x.data.metrics.total,1);});

test('public branded links reject reserved names and profile conflicts',async()=>{let x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brandSlug:'admin',destinationUrl:'https://example.com'})});assert.equal(x.r.status,400);await createProfile('profile-link');x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brandSlug:'profile-link',destinationUrl:'https://example.com'})});assert.equal(x.r.status,409);x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brandSlug:'qr-link',destinationUrl:'https://example.com'})});assert.equal(x.r.status,201);const y=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'qr-link',name:'Conflict'})});assert.equal(y.r.status,409);});

test('branded QR HEAD does not count and pause/resume keeps the same link',async()=>{const created=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brandSlug:'stable-brand',destinationUrl:'https://example.com/stable'})});assert.equal(created.r.status,201);let r=await fetch(created.data.redirectUrl,{method:'HEAD',redirect:'manual'});assert.equal(r.status,302);let x=await j(`/api/manage/qrs/${created.data.qr.id}`,{headers:{'x-manage-token':created.data.manageToken}});assert.equal(x.data.metrics.total,0);x=await j(`/api/manage/qrs/${created.data.qr.id}`,{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':created.data.manageToken},body:JSON.stringify({isActive:false})});assert.equal(x.r.status,200);r=await fetch(created.data.redirectUrl,{redirect:'manual'});assert.equal(r.status,404);x=await j(`/api/manage/qrs/${created.data.qr.id}`,{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':created.data.manageToken},body:JSON.stringify({isActive:true})});assert.equal(x.r.status,200);r=await fetch(created.data.redirectUrl,{headers:ua,redirect:'manual'});assert.equal(r.status,302);x=await j(`/api/manage/qrs/${created.data.qr.id}`,{headers:{'x-manage-token':created.data.manageToken}});assert.equal(x.data.metrics.total,1);});

test('profile creation validates clean unique and reserved slugs',async()=>{const p=await createProfile('ajn-alpha');assert.equal(p.profile.slug,'ajn-alpha');assert.match(p.publicUrl,/\/ajn-alpha$/);assert.match(p.manageUrl,/\/manage\/profile\/ajn-alpha\//);let x=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'ajn-alpha',name:'Duplicate'})});assert.equal(x.r.status,409);x=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'admin',name:'Admin'})});assert.equal(x.r.status,400);x=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'create-profile',name:'Reserved'})});assert.equal(x.r.status,400);});


test('profile appearance template and accent persist safely',async()=>{const p=await createProfile('appearance-test');assert.deepEqual(p.profile.appearance,{template:'professional',accent:'ocean'});let x=await j('/api/manage/profiles/appearance-test',{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':p.manageToken},body:JSON.stringify({appearance:{template:'creator',accent:'rose'}})});assert.equal(x.r.status,200);assert.deepEqual(x.data.profile.appearance,{template:'creator',accent:'rose'});x=await j('/api/manage/profiles/appearance-test',{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':p.manageToken},body:JSON.stringify({appearance:{template:'unknown',accent:'ocean'}})});assert.equal(x.r.status,400);});

test('public profile HTML has profile-specific SEO metadata',async()=>{const p=await createProfile('ajn-seo');const r=await fetch(`${base}/ajn-seo`);assert.equal(r.status,200);const html=await r.text();assert.match(html,/<title>Sample Business · QR AJN<\/title>/);assert.match(html,new RegExp(`canonical\" href=\"${base.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\/ajn-seo`));assert.match(html,/Professional public profile/);});

test('public profile view, QR scan and click analytics are separate',async()=>{const p=await createProfile('ajn-metrics');let r=await fetch(`${base}/ajn-metrics`,{headers:ua,redirect:'manual'});assert.equal(r.status,200);r=await fetch(p.profileQrUrl,{headers:ua,redirect:'manual'});assert.equal(r.status,302);assert.match(r.headers.get('location'),/\/ajn-metrics\?from=qr$/);let x=await j('/api/profiles/ajn-metrics/actions',{method:'POST',headers:{'content-type':'application/json',...ua},body:JSON.stringify({action:'whatsapp',label:'WhatsApp'})});assert.equal(x.r.status,201);x=await j('/api/manage/profiles/ajn-metrics',{headers:{'x-manage-token':p.manageToken}});assert.equal(x.r.status,200);assert.equal(x.data.metrics.qrScans.total,1);assert.equal(x.data.metrics.profileViews.total,1);assert.equal(x.data.metrics.totalActions,1);assert.ok(x.data.metrics.uniqueApprox>=1);assert.equal(x.data.topActions[0].label,'whatsapp');});

test('profile edit keeps public slug and QR route stable',async()=>{const p=await createProfile('ajn-edit');const oldQr=p.profileQrUrl;let x=await j('/api/manage/profiles/ajn-edit',{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':p.manageToken},body:JSON.stringify({name:'Updated Business',website:'https://openai.com',isActive:true,appearance:{template:'business',accent:'emerald'}})});assert.equal(x.r.status,200);assert.equal(x.data.profile.slug,'ajn-edit');assert.equal(x.data.profile.profileQrUrl,oldQr);assert.equal(x.data.profile.name,'Updated Business');assert.deepEqual(x.data.profile.appearance,{template:'business',accent:'emerald'});});

test('wrong management token is rejected',async()=>{await createProfile('ajn-secret');const x=await j('/api/manage/profiles/ajn-secret',{headers:{'x-manage-token':'wrong-token-value-that-is-long-enough'}});assert.equal(x.r.status,403);});

test('logo upload and public media route work',async()=>{const p=await createProfile('ajn-media');const png=Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489','hex');let r=await fetch(`${base}/api/manage/profiles/ajn-media/media/logo`,{method:'PUT',headers:{'content-type':'image/png','x-manage-token':p.manageToken},body:png});assert.equal(r.status,200);const data=await r.json();assert.match(data.profile.media.logo,/\/media\//);r=await fetch(data.profile.media.logo);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');const x=await j('/api/manage/profiles/ajn-media',{method:'DELETE',headers:{'x-manage-token':p.manageToken}});assert.equal(x.r.status,200);});

test('PDF gets clean profile path, view/share analytics and delete',async()=>{const p=await createProfile('ajn-docs');const pdf=Buffer.from('%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF\n');let r=await fetch(`${base}/api/manage/profiles/ajn-docs/documents`,{method:'POST',headers:{'content-type':'application/pdf','x-manage-token':p.manageToken,'x-document-title':'Company Brochure','x-document-slug':'brochure'},body:pdf});assert.equal(r.status,201);let data=await r.json();assert.equal(data.document.url,`${base}/ajn-docs/brochure`);r=await fetch(data.document.url,{headers:ua});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');let x=await j('/api/profiles/ajn-docs/documents/brochure/share',{method:'POST',headers:ua});assert.equal(x.r.status,201);x=await j('/api/manage/profiles/ajn-docs',{headers:{'x-manage-token':p.manageToken}});assert.equal(x.data.metrics.documentViews,1);assert.equal(x.data.metrics.documentShares,1);assert.equal(x.data.documents[0].views,1);assert.equal(x.data.documents[0].shares,1);x=await j('/api/manage/profiles/ajn-docs/documents/brochure',{method:'DELETE',headers:{'x-manage-token':p.manageToken}});assert.equal(x.r.status,200);r=await fetch(`${base}/ajn-docs/brochure`);assert.equal(r.status,404);});

test('profile pause blocks public page and QR, resume restores it',async()=>{const p=await createProfile('ajn-pause');let x=await j('/api/manage/profiles/ajn-pause',{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':p.manageToken},body:JSON.stringify({isActive:false})});assert.equal(x.r.status,200);let r=await fetch(`${base}/ajn-pause`);assert.equal(r.status,404);r=await fetch(p.profileQrUrl,{redirect:'manual'});assert.equal(r.status,404);x=await j('/api/manage/profiles/ajn-pause',{method:'PATCH',headers:{'content-type':'application/json','x-manage-token':p.manageToken},body:JSON.stringify({isActive:true})});assert.equal(x.r.status,200);r=await fetch(`${base}/ajn-pause`);assert.equal(r.status,200);});

test('profile delete removes resource and analytics',async()=>{const p=await createProfile('ajn-delete');await fetch(`${base}/ajn-delete`,{headers:ua});const x=await j('/api/manage/profiles/ajn-delete',{method:'DELETE',headers:{'x-manage-token':p.manageToken}});assert.equal(x.r.status,200);const r=await fetch(`${base}/ajn-delete`);assert.equal(r.status,404);});

test('existing trackable QR flow remains functional',async()=>{let x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Menu',destinationUrl:'https://example.com/menu'})});assert.equal(x.r.status,201);const q=x.data;let r=await fetch(q.redirectUrl,{headers:ua,redirect:'manual'});assert.equal(r.status,302);x=await j(`/api/manage/qrs/${q.qr.id}`,{headers:{'x-manage-token':q.manageToken}});assert.equal(x.r.status,200);assert.equal(x.data.metrics.total,1);});

test('concurrent scans are serialized without lost counts',async()=>{let x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Concurrency test',destinationUrl:'https://example.com/target'})});assert.equal(x.r.status,201);const q=x.data;const scans=12;const responses=await Promise.all(Array.from({length:scans},()=>fetch(q.redirectUrl,{headers:ua,redirect:'manual'})));for(const r of responses)assert.equal(r.status,302);x=await j(`/api/manage/qrs/${q.qr.id}`,{headers:{'x-manage-token':q.manageToken}});assert.equal(x.r.status,200);assert.equal(x.data.metrics.total,scans);assert.equal(x.data.metrics.total,x.data.metrics.today);});

test('unsafe URL schemes are rejected',async()=>{let x=await j('/api/qrs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Bad',destinationUrl:'javascript:alert(1)'})});assert.equal(x.r.status,400);x=await j('/api/profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'ajn-bad',name:'Bad',website:'javascript:alert(1)'})});assert.equal(x.r.status,400);});
