import {createQrMatrix, drawMatrixToCanvas, matrixToSvg, isQrContrastSafe} from './qr-encoder.js';

const $ = id => document.getElementById(id);
const state = {
  mode:'static', matrix:null, payload:'', qrManageId:'', qrManageToken:'', currentManagedQr:null,
  profileManageSlug:'', profileManageToken:'', currentManagedProfile:null, publicProfile:null,
  createdProfile:null, createdProfileManageUrl:'', previewLogoUrl:'', previewCoverUrl:'', refreshTimer:null,
  refreshHandler:null, qrLogoDataUrl:'', profileChartMode:'scans', qrChartRange:30, profileChartRange:30, profileDirty:false, profileDraftTimer:null
};
const types = {
  url:{label:'Website URL',fields:[['url','Website URL','url','https://example.com']]},
  text:{label:'Text',fields:[['text','Text','textarea','Write any text']]},
  wifi:{label:'Wi-Fi',fields:[['ssid','Network name (SSID)','text','My WiFi'],['password','Password','text',''],['security','Security','select','WPA'],['hidden','Hidden network','checkbox','false']]},
  phone:{label:'Phone',fields:[['phone','Phone number','tel','+000000000000']]},
  sms:{label:'SMS',fields:[['phone','Phone number','tel','+000000000000'],['message','Message','textarea','Hello']]},
  email:{label:'Email',fields:[['email','Email address','email','hello@example.com'],['subject','Subject','text','Hello'],['body','Message','textarea','']]},
  whatsapp:{label:'WhatsApp',fields:[['phone','WhatsApp number','tel','+000000000000'],['message','Message','textarea','Hello']]},
  location:{label:'Location',fields:[['lat','Latitude','text','0.0000'],['lng','Longitude','text','0.0000'],['label','Place label','text','Your location']]},
  vcard:{label:'Contact / vCard',fields:[['name','Full name','text','Your Name'],['org','Organization','text',''],['phone','Phone','tel','+000000000000'],['email','Email','email',''],['website','Website','url','https://example.com']]}
};
const qrTemplates = {
  minimal:{foreground:'#0f172a',eyeColor:'#0f172a',background:'#ffffff',moduleStyle:'square',eyeStyle:'square',ecc:'M'},
  business:{foreground:'#172554',eyeColor:'#0f172a',background:'#ffffff',moduleStyle:'rounded',eyeStyle:'square',ecc:'H'},
  professional:{foreground:'#27272a',eyeColor:'#18181b',background:'#fafafa',moduleStyle:'rounded',eyeStyle:'rounded',ecc:'Q'},
  social:{foreground:'#4f46e5',eyeColor:'#312e81',background:'#ffffff',moduleStyle:'dots',eyeStyle:'rounded',ecc:'H'},
  ocean:{foreground:'#075985',eyeColor:'#0c4a6e',background:'#f8fdff',moduleStyle:'rounded',eyeStyle:'rounded',ecc:'Q'},
  emerald:{foreground:'#047857',eyeColor:'#064e3b',background:'#ffffff',moduleStyle:'dots',eyeStyle:'rounded',ecc:'H'}
};

init();

function init(){
  bind(); renderStaticFields(); updateContrast(); updateScanQuality(); updatePreviewSurface(); updatePreviewFrame(); addCustomLinkRow('customLinksEditor'); updateProfilePreview(); checkProfileDraft(); route();
}

function bind(){
  $('staticMode').addEventListener('click',()=>setMode('static')); $('trackMode').addEventListener('click',()=>setMode('track')); $('qrType').addEventListener('change',()=>{renderStaticFields();resetPreview();});
  for(const [id,panel] of [['contentTab','contentPanel'],['customizeTab','customizePanel'],['advancedTab','advancedPanel']]) $(id).addEventListener('click',()=>showCreatorTab(id,panel));
  for(const el of document.querySelectorAll('[data-qr-template]')) el.addEventListener('click',()=>applyQrTemplate(el.dataset.qrTemplate,el));
  for(const el of document.querySelectorAll('#qrColorPresets button')) el.addEventListener('click',()=>applyQrColors(el));
  $('resetQrDesign').addEventListener('click',()=>applyQrTemplate('minimal',document.querySelector('[data-qr-template="minimal"]')));
  for(const id of ['foreground','eyeColor','background','moduleStyle','eyeStyle','ecc','qrMargin','qrSize','transparentBackground','frameStyle','frameText']) $(id).addEventListener('input',()=>{updateContrast();updateScanQuality();updatePreviewFrame();rerenderCurrentQr();});
  $('logoSize').addEventListener('input',()=>{$('logoSizeValue').textContent=`${$('logoSize').value}%`;updateScanQuality();rerenderCurrentQr();});
  $('qrMargin').addEventListener('input',()=>{$('marginValue').textContent=`${$('qrMargin').value} modules`;updateScanQuality();});
  $('previewSurface').addEventListener('change',()=>{updatePreviewSurface();updatePreviewFrame();}); $('qrLogo').addEventListener('change',loadQrLogo);
  $('generateButton').addEventListener('click',generate); $('mobileGenerateQr').addEventListener('click',generate); $('mobilePreviewQr').addEventListener('click',()=>{$('qrPreviewStage').scrollIntoView({behavior:'smooth',block:'center'});});
  $('downloadPng').addEventListener('click',()=>downloadPng('qr-ajn')); $('downloadSvg').addEventListener('click',downloadSvg); $('copyQrContent').addEventListener('click',()=>copyText(state.payload)); $('shareQr').addEventListener('click',shareCurrentQr);
  $('copyManageUrl').addEventListener('click',()=>copyText($('manageUrlOutput').value)); $('openManageButton').addEventListener('click',()=>$('manageDialog').showModal()); $('openPastedManageLink').addEventListener('click',openPastedManageLink);
  $('editQrForm').addEventListener('submit',saveManagedQr); $('activeToggle').addEventListener('change',toggleManagedQr); $('copyManagedQrLink').addEventListener('click',()=>copyText(managedRedirectUrl())); $('downloadManagedPng').addEventListener('click',downloadManagedPng); $('deleteManagedQr').addEventListener('click',deleteManagedQr);
  $('profileCreateForm').addEventListener('submit',createProfile); $('profileCreateForm').addEventListener('input',scheduleProfileDraft); $('profileCreateForm').addEventListener('change',scheduleProfileDraft); $('addCustomLink').addEventListener('click',()=>{addCustomLinkRow('customLinksEditor');scheduleProfileDraft();}); $('profileSlug').addEventListener('input',sanitizeSlugInput);
  for(const id of ['profileName','profileCategory','profileTagline','profileAbout','profileSlug']) $(id).addEventListener('input',updateProfilePreview); $('profileAccent').addEventListener('change',()=>{updateProfilePreview();scheduleProfileDraft();});
  for(const el of document.querySelectorAll('[data-profile-template]')) el.addEventListener('click',()=>selectProfileTemplate(el.dataset.profileTemplate,el));
  $('profileLogo').addEventListener('change',()=>previewBuilderImage('logo')); $('profileCover').addEventListener('change',()=>previewBuilderImage('cover')); $('restoreProfileDraft').addEventListener('click',restoreProfileDraft); $('discardProfileDraft').addEventListener('click',discardProfileDraft);
  $('copyCreatedPublic').addEventListener('click',()=>copyText($('createdPublicUrl').value)); $('copyCreatedManage').addEventListener('click',()=>copyText($('createdManageUrl').value)); $('downloadCreatedProfileQr').addEventListener('click',downloadCreatedProfileQr);
  $('sharePublicProfile').addEventListener('click',sharePublicProfile); $('copyPublicProfile').addEventListener('click',copyCurrentPublicProfile); $('downloadPublicQr').addEventListener('click',downloadPublicProfileQr);
  $('profileEditForm').addEventListener('submit',saveManagedProfile); $('profileEditForm').addEventListener('input',markProfileDirty); $('profileEditForm').addEventListener('change',markProfileDirty); $('profileActiveToggle').addEventListener('change',toggleManagedProfile); $('addEditCustomLink').addEventListener('click',()=>{addCustomLinkRow('editCustomLinksEditor');markProfileDirty();});
  $('copyProfilePublicLink').addEventListener('click',()=>state.currentManagedProfile&&copyText(state.currentManagedProfile.profile.publicUrl)); $('shareManagedProfile').addEventListener('click',shareManagedProfile); $('downloadManagedProfileQr').addEventListener('click',downloadManagedProfileQr);
  $('profileChartScans').addEventListener('click',()=>setProfileChartMode('scans')); $('profileChartViews').addEventListener('click',()=>setProfileChartMode('views')); $('profileChartActions').addEventListener('click',()=>setProfileChartMode('clicks'));
  $('qrRangeToday').addEventListener('click',()=>setAnalyticsRange('qr',1)); $('qrRange7').addEventListener('click',()=>setAnalyticsRange('qr',7)); $('qrRange30').addEventListener('click',()=>setAnalyticsRange('qr',30));
  $('profileRangeToday').addEventListener('click',()=>setAnalyticsRange('profile',1)); $('profileRange7').addEventListener('click',()=>setAnalyticsRange('profile',7)); $('profileRange30').addEventListener('click',()=>setAnalyticsRange('profile',30));
  $('uploadManagedLogo').addEventListener('click',()=>uploadManagedMedia('logo')); $('uploadManagedCover').addEventListener('click',()=>uploadManagedMedia('cover')); $('removeManagedLogo').addEventListener('click',()=>removeManagedMedia('logo')); $('removeManagedCover').addEventListener('click',()=>removeManagedMedia('cover'));
  $('documentUploadForm').addEventListener('submit',uploadManagedDocument); $('documentTitle').addEventListener('input',()=>{if(!$('documentSlug').dataset.touched)$('documentSlug').value=slugify($('documentTitle').value).slice(0,60);}); $('documentSlug').addEventListener('input',()=>{$('documentSlug').dataset.touched='1';$('documentSlug').value=slugify($('documentSlug').value).slice(0,60);});
  $('deleteManagedProfile').addEventListener('click',deleteManagedProfile); window.addEventListener('popstate',route); document.addEventListener('visibilitychange',handleVisibilityChange); window.addEventListener('beforeunload',e=>{if(state.profileDirty){e.preventDefault();e.returnValue='';}});
}

function route(){
  clearRefresh(); hideAllViews(); const profileManage=parseProfileManageRoute(location.pathname); const qrManage=parseQrManageRoute(location.pathname);
  if(profileManage){showProfileManage(profileManage.slug,profileManage.token);return;} if(qrManage){showQrManage(qrManage.id,qrManage.token);return;}
  if(/^\/[a-z0-9-]{3,40}\/?$/.test(location.pathname)&&!['/privacy','/terms','/contact','/about','/create','/create-profile'].includes(location.pathname)){showPublicProfile(location.pathname.replace(/^\//,'').replace(/\/$/,''));return;}
  showHome();
}
function hideAllViews(){for(const id of ['homeView','publicProfileView','qrManageView','profileManageView'])$(id).classList.add('hidden');}
function showHome(){$('homeView').classList.remove('hidden');document.title='QR AJN — QR Codes, Public Profiles & Live Analytics';}

// ---------------- QR creator ----------------
function setMode(mode){state.mode=mode;$('staticMode').classList.toggle('active',mode==='static');$('trackMode').classList.toggle('active',mode==='track');$('staticMode').setAttribute('aria-selected',String(mode==='static'));$('trackMode').setAttribute('aria-selected',String(mode==='track'));$('staticFields').classList.toggle('hidden',mode!=='static');$('trackFields').classList.toggle('hidden',mode!=='track');$('generateButton').textContent=mode==='track'?'Create trackable QR':'Generate QR';$('mobileGenerateQr').textContent=$('generateButton').textContent;$('manageSuccess').classList.add('hidden');setMessage('creatorMessage','');resetPreview();}
function showCreatorTab(buttonId,panelId){for(const id of ['contentTab','customizeTab','advancedTab']){$(id).classList.toggle('active',id===buttonId);$(id).setAttribute('aria-selected',String(id===buttonId));}for(const id of ['contentPanel','customizePanel','advancedPanel'])$(id).classList.toggle('hidden',id!==panelId);}
function renderStaticFields(){const t=types[$('qrType').value]||types.url;const host=$('payloadFields');host.replaceChildren();const wrap=document.createElement('div');wrap.className='form-stack';for(const [key,label,typeName,placeholder] of t.fields){const lab=document.createElement('label');lab.textContent=label;let input;if(typeName==='textarea'){input=document.createElement('textarea');input.rows=3;input.placeholder=placeholder;}else if(typeName==='select'){input=document.createElement('select');for(const v of ['WPA','WEP','nopass']){const o=document.createElement('option');o.value=v;o.textContent=v==='nopass'?'No password':v;input.append(o);}}else if(typeName==='checkbox'){input=document.createElement('input');input.type='checkbox';input.id=`field-${key}`;lab.append(input);wrap.append(lab);continue;}else{input=document.createElement('input');input.type=typeName;input.placeholder=placeholder;}input.id=`field-${key}`;input.autocomplete='off';input.maxLength=typeName==='textarea'?1400:500;lab.append(input);wrap.append(lab);}host.append(wrap);}
function applyQrTemplate(name,button){const t=qrTemplates[name]||qrTemplates.minimal;$('foreground').value=t.foreground;$('eyeColor').value=t.eyeColor;$('background').value=t.background;$('moduleStyle').value=t.moduleStyle;$('eyeStyle').value=t.eyeStyle;$('ecc').value=t.ecc;$('transparentBackground').checked=false;for(const el of document.querySelectorAll('[data-qr-template]'))el.classList.toggle('active',el===button);updateContrast();updateScanQuality();rerenderCurrentQr();}
function applyQrColors(el){$('foreground').value=el.dataset.fg;$('eyeColor').value=el.dataset.eye||el.dataset.fg;$('background').value=el.dataset.bg||'#ffffff';$('transparentBackground').checked=false;updateContrast();updateScanQuality();rerenderCurrentQr();}
function updatePreviewSurface(){const stage=$('qrPreviewStage');const frame=$('frameStyle')?.value||'none';stage.className=`qr-preview-stage surface-${$('previewSurface').value} frame-${frame}`;}
function updatePreviewFrame(){const stage=$('qrPreviewStage');updatePreviewSurface();stage.dataset.frameText=cleanFrameText($('frameText')?.value||'SCAN ME');}
function loadQrLogo(){const file=$('qrLogo').files[0];state.qrLogoDataUrl='';if(!file){updateScanQuality();rerenderCurrentQr();return;}if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){$('qrLogo').value='';toast('Use a PNG, JPEG or WebP logo up to 2 MB.','error');return;}const reader=new FileReader();reader.onload=()=>{state.qrLogoDataUrl=String(reader.result||'');if($('ecc').value==='L'||$('ecc').value==='M')$('ecc').value='H';updateScanQuality();rerenderCurrentQr();};reader.readAsDataURL(file);}
async function generate(){setMessage('creatorMessage','');$('manageSuccess').classList.add('hidden');try{if(!$('transparentBackground').checked&&!isQrContrastSafe($('foreground').value,$('background').value))throw new Error('Increase color contrast before generating.');if(state.mode==='track')await createTrackable();else await renderQr(buildStaticPayload(),false);showCreatorTab('customizeTab','customizePanel');}catch(e){setMessage('creatorMessage',friendlyError(e),'error');}}
function buildStaticPayload(){const type=$('qrType').value;const value=k=>String($(`field-${k}`)?.value||'').trim();switch(type){case'url':return requireHttpUrl(value('url'));case'text':if(!value('text'))throw new Error('Enter text to encode.');return value('text');case'wifi':{const ssid=value('ssid');if(!ssid)throw new Error('Enter the Wi-Fi network name.');return `WIFI:T:${wifiEscape(value('security')||'WPA')};S:${wifiEscape(ssid)};P:${wifiEscape(value('password'))};H:${$('field-hidden')?.checked?'true':'false'};;`;}case'phone':{const phone=phoneClean(value('phone'));if(!phone)throw new Error('Enter a phone number.');return `tel:${phone}`;}case'sms':{const phone=phoneClean(value('phone'));if(!phone)throw new Error('Enter a phone number.');return `SMSTO:${phone}:${value('message')}`;}case'email':{const email=value('email');if(!validEmail(email))throw new Error('Enter a valid email address.');const q=new URLSearchParams();if(value('subject'))q.set('subject',value('subject'));if(value('body'))q.set('body',value('body'));return `mailto:${email}${q.toString()?`?${q}`:''}`;}case'whatsapp':{const phone=phoneClean(value('phone')).replace(/^\+/,'');if(!phone)throw new Error('Enter a WhatsApp number.');return `https://wa.me/${phone}${value('message')?`?text=${encodeURIComponent(value('message'))}`:''}`;}case'location':{const lat=Number(value('lat')),lng=Number(value('lng'));if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lng)||lng<-180||lng>180)throw new Error('Enter valid latitude and longitude.');const label=value('label');return `geo:${lat},${lng}${label?`?q=${lat},${lng}(${encodeURIComponent(label)})`:''}`;}case'vcard':{const name=vcard(value('name'));if(!name)throw new Error('Enter a contact name.');const lines=['BEGIN:VCARD','VERSION:3.0',`FN:${name}`];if(value('org'))lines.push(`ORG:${vcard(value('org'))}`);if(value('phone'))lines.push(`TEL:${vcard(phoneClean(value('phone')))}`);if(value('email'))lines.push(`EMAIL:${vcard(value('email'))}`);if(value('website'))lines.push(`URL:${requireHttpUrl(value('website'))}`);lines.push('END:VCARD');return lines.join('\n');}default:throw new Error('Choose a QR type.');}}
async function createTrackable(){const name=$('trackName').value.trim()||'Trackable QR';const destinationUrl=requireHttpUrl($('trackDestination').value);$('generateButton').disabled=true;$('mobileGenerateQr').disabled=true;setMessage('creatorMessage','Creating private analytics link...');try{const r=await api('/api/qrs',{method:'POST',body:{name,destinationUrl}});await renderQr(r.redirectUrl,true);$('manageUrlOutput').value=r.manageUrl;$('openAnalyticsLink').href=r.manageUrl;$('manageSuccess').classList.remove('hidden');setMessage('creatorMessage','Trackable QR created. Save the private analytics link.','success');}finally{$('generateButton').disabled=false;$('mobileGenerateQr').disabled=false;}}
function qrRenderOptions(size=560){return {size,margin:Number($('qrMargin').value||4),foreground:$('foreground').value,background:$('background').value,style:$('moduleStyle').value,eyeStyle:$('eyeStyle').value,eyeColor:$('eyeColor').value,transparent:$('transparentBackground').checked};}
async function renderQr(payload,trackable){const matrix=createQrMatrix(payload,{level:$('ecc').value});state.matrix=matrix;state.payload=payload;const canvas=document.createElement('canvas');drawMatrixToCanvas(canvas,matrix.matrix,qrRenderOptions(560));await applyLogoToCanvas(canvas);$('qrPreview').replaceChildren(canvas);$('previewTitle').textContent=trackable?'Trackable QR ready':`${types[$('qrType').value]?.label||'QR'} ready`;$('qrStatus').textContent=trackable?'TRACKABLE':'READY';$('qrStatus').className=`status ${trackable?'trackable':'ready'}`;for(const id of ['downloadPng','downloadSvg','copyQrContent','shareQr'])$(id).disabled=false;updateScanQuality();}
function rerenderCurrentQr(){if(!state.matrix||!state.payload)return;renderQr(state.payload,state.mode==='track').catch(()=>{});}
function resetPreview(){state.matrix=null;state.payload='';$('qrPreview').innerHTML='<div class="qr-placeholder"><span class="qr-placeholder-icon">▦</span><strong>Your QR appears here</strong><small>Configure the content and generate when ready.</small></div>';$('previewTitle').textContent='Ready to create';$('qrStatus').textContent='WAITING';$('qrStatus').className='status';for(const id of ['downloadPng','downloadSvg','copyQrContent','shareQr'])$(id).disabled=true;updateScanQuality();}
function updateContrast(){const safe=$('transparentBackground').checked||isQrContrastSafe($('foreground').value,$('background').value);$('contrastWarning').classList.toggle('hidden',safe);}
function updateScanQuality(){const transparent=$('transparentBackground').checked;const contrast=transparent?false:isQrContrastSafe($('foreground').value,$('background').value);const margin=Number($('qrMargin').value||4);const logo=Boolean(state.qrLogoDataUrl);const logoSize=Number($('logoSize').value||16);const ecc=$('ecc').value;let score=100;const notes=[];if(transparent){score-=24;notes.push('transparent background depends on placement');}else if(!contrast){score-=55;notes.push('increase color contrast');}if(margin<4){score-=18;notes.push('use a 4-module quiet zone');}if(logo&&logoSize>18){score-=18;notes.push('reduce logo size');}if(logo&&!['Q','H'].includes(ecc)){score-=22;notes.push('use Q or H error correction with a logo');}const dot=$('scanQualityDot'),label=$('scanQualityLabel'),detail=$('scanQualityDetail');dot.className='quality-dot';if(!state.matrix){dot.classList.add('neutral');label.textContent='Waiting for QR';detail.textContent='Use a high-contrast design for reliable scanning.';return;}if(score>=90){dot.classList.add('good');label.textContent='Excellent';detail.textContent=logo?'High contrast · protected quiet zone · logo-safe ECC':'High contrast · protected quiet zone';}else if(score>=70){dot.classList.add('warn');label.textContent='Good with caution';detail.textContent=notes.join(' · ')||'Test the final QR on a real phone.';}else{dot.classList.add('bad');label.textContent='Needs attention';detail.textContent=notes.join(' · ')||'Adjust the design before sharing.';}}
async function applyLogoToCanvas(canvas){if(!state.qrLogoDataUrl)return canvas;const img=await loadImage(state.qrLogoDataUrl);const ctx=canvas.getContext('2d');ctx.save();ctx.setTransform(1,0,0,1,0,0);const physical=canvas.width;const logoSize=Math.round(physical*(Number($('logoSize').value||16)/100));const pad=Math.max(8,Math.round(logoSize*.14));const box=logoSize+pad*2;const x=Math.round((physical-box)/2),y=Math.round((physical-box)/2);ctx.fillStyle='#ffffff';roundedRect(ctx,x,y,box,box,Math.round(box*.18));ctx.fill();ctx.drawImage(img,x+pad,y+pad,logoSize,logoSize);ctx.restore();return canvas;}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Could not load QR logo.'));img.src=src;});}
function roundedRect(ctx,x,y,w,h,r){if(typeof ctx.roundRect==='function'){ctx.beginPath();ctx.roundRect(x,y,w,h,r);return;}ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
async function createExportCanvas(){if(!state.matrix)return null;const size=Number($('qrSize').value||1024);const frame=$('frameStyle')?.value||'none';const qrSize=frame==='none'?size:Math.round(size*(frame==='label'?.78:.86));const qr=document.createElement('canvas');drawMatrixToCanvas(qr,state.matrix.matrix,{...qrRenderOptions(qrSize),pixelRatio:1});await applyLogoToCanvas(qr);if(frame==='none')return qr;const out=document.createElement('canvas');out.width=size;out.height=size;out.style.width=`${size}px`;out.style.height=`${size}px`;const ctx=out.getContext('2d');ctx.fillStyle='#ffffff';roundedRect(ctx,0,0,size,size,Math.round(size*.055));ctx.fill();ctx.strokeStyle='#e5e7eb';ctx.lineWidth=Math.max(1,Math.round(size*.002));ctx.stroke();const x=Math.round((size-qrSize)/2);const y=frame==='label'?Math.round(size*.055):Math.round((size-qrSize)/2);ctx.drawImage(qr,x,y,qrSize,qrSize);if(frame==='label'){const label=cleanFrameText($('frameText')?.value||'SCAN ME');ctx.fillStyle=$('eyeColor').value||'#111827';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`800 ${Math.max(18,Math.round(size*.045))}px Manrope, Arial, sans-serif`;ctx.fillText(label,size/2,Math.round(size*.92),size*.78);}return out;}
async function downloadPng(baseName){const canvas=await createExportCanvas();if(!canvas)return;canvas.toBlob(b=>downloadBlob(b,`${safeFilename(baseName)}.png`),'image/png');}
function svgWithLogo(size){let svg=matrixToSvg(state.matrix.matrix,{...qrRenderOptions(size),title:'QR AJN QR code'});if(state.qrLogoDataUrl){const logoSize=Math.round(size*(Number($('logoSize').value||16)/100));const pad=Math.round(logoSize*.14);const box=logoSize+pad*2;const x=Math.round((size-box)/2),y=x;const href=state.qrLogoDataUrl.replace(/["<>]/g,'');svg=svg.replace('</svg>',`<rect x="${x}" y="${y}" width="${box}" height="${box}" rx="${Math.round(box*.18)}" fill="#fff"/><image href="${href}" x="${x+pad}" y="${y+pad}" width="${logoSize}" height="${logoSize}" preserveAspectRatio="xMidYMid meet"/></svg>`);}return svg;}
function downloadSvg(){if(!state.matrix)return;const size=Number($('qrSize').value||1024);const frame=$('frameStyle')?.value||'none';let svg;if(frame==='none')svg=svgWithLogo(size);else{const qrSize=Math.round(size*(frame==='label'?.78:.86));const q=svgWithLogo(qrSize);const inner=q.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');const x=Math.round((size-qrSize)/2);const y=frame==='label'?Math.round(size*.055):Math.round((size-qrSize)/2);const label=svgEscape(cleanFrameText($('frameText')?.value||'SCAN ME'));svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" role="img" aria-label="QR AJN QR code"><rect width="${size}" height="${size}" rx="${Math.round(size*.055)}" fill="#fff" stroke="#e5e7eb" stroke-width="${Math.max(1,Math.round(size*.002))}"/><g transform="translate(${x} ${y})">${inner}</g>${frame==='label'?`<text x="${size/2}" y="${Math.round(size*.925)}" text-anchor="middle" dominant-baseline="middle" font-family="Manrope,Arial,sans-serif" font-size="${Math.max(18,Math.round(size*.045))}" font-weight="800" letter-spacing="${Math.max(1,Math.round(size*.006))}" fill="${$('eyeColor').value||'#111827'}">${label}</text>`:''}</svg>`;}downloadBlob(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),`${safeFilename(state.mode==='track'?'trackable-qr':$('qrType').value)}.svg`);}
async function shareCurrentQr(){if(!state.payload)return;try{const canvas=await createExportCanvas();if(canvas&&navigator.share&&navigator.canShare){const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=new File([blob],'qr-ajn.png',{type:'image/png'});if(navigator.canShare({files:[file]})){await navigator.share({title:'QR AJN QR code',text:'QR code created with QR AJN',files:[file]});return;}}}catch{}await copyText(state.payload);toast('QR content copied.','success');}
// ---------------- Trackable QR management ----------------
async function showQrManage(id,token){state.qrManageId=id;state.qrManageToken=token;$('qrManageView').classList.remove('hidden');document.title='QR Analytics · QR AJN';await refreshQrManage(true);startSmartRefresh(()=>refreshQrManage(false));}
async function refreshQrManage(first){try{const data=await api(`/api/manage/qrs/${encodeURIComponent(state.qrManageId)}`,{headers:{'x-manage-token':state.qrManageToken}});state.currentManagedQr=data;renderQrManage(data,first);$('manageError').classList.add('hidden');$('manageContent').classList.remove('hidden');$('manageLiveText').textContent='Live · updated just now';}catch(e){$('manageLiveText').textContent='Connection interrupted · retrying';if(first){$('manageContent').classList.add('hidden');$('manageError').textContent=friendlyError(e);$('manageError').classList.remove('hidden');}}}
function renderQrManage(data,fillEditor=false){const {qr,metrics}=data;$('manageHeading').textContent=qr.name;$('manageSubheading').textContent=`Created ${formatDate(qr.createdAt)} · private analytics`;$('manageQrName').textContent=qr.name;$('manageDestinationLink').textContent=qr.destinationUrl;$('manageDestinationLink').href=qr.destinationUrl;$('activeToggle').checked=qr.isActive;$('activeLabel').textContent=qr.isActive?'Active':'Paused';if(fillEditor||!['editName','editDestination'].includes(document.activeElement?.id)){$('editName').value=qr.name;$('editDestination').value=qr.destinationUrl;}setMetricValue('metricTotal',metrics.total,fillEditor);setMetricValue('metricToday',metrics.today,fillEditor);$('metric7').textContent=formatNumber(metrics.last7);setMetricValue('metric30',metrics.last30,fillEditor);setMetricValue('metricUnique',metrics.uniqueApprox,fillEditor);renderQrInto('manageQrCanvas',managedRedirectUrl(),248);renderLineChart('dailyChart',filterDaily(data.daily,state.qrChartRange),'count','Scans');renderBreakdown('deviceBreakdown',data.devices,'No scans yet.');renderBreakdown('qrBrowserBreakdown',data.browsers||[],'No browser data yet.');}
function managedRedirectUrl(){return state.currentManagedQr?`${location.origin}/r/${state.currentManagedQr.qr.slug}`:'';}
async function saveManagedQr(e){e.preventDefault();try{await api(`/api/manage/qrs/${encodeURIComponent(state.qrManageId)}`,{method:'PATCH',headers:{'x-manage-token':state.qrManageToken},body:{name:$('editName').value,destinationUrl:$('editDestination').value}});setMessage('manageMessage','Changes saved. The QR code itself did not change.','success');await refreshQrManage(false);}catch(err){setMessage('manageMessage',err.message,'error');}}
async function toggleManagedQr(){try{await api(`/api/manage/qrs/${encodeURIComponent(state.qrManageId)}`,{method:'PATCH',headers:{'x-manage-token':state.qrManageToken},body:{isActive:$('activeToggle').checked}});await refreshQrManage(false);}catch(e){$('activeToggle').checked=!$('activeToggle').checked;setMessage('manageMessage',e.message,'error');}}
function downloadManagedPng(){if(!state.currentManagedQr)return;downloadCanvasFromHost('manageQrCanvas',`${safeFilename(state.currentManagedQr.qr.name)}-trackable.png`);}
async function deleteManagedQr(){if(!confirm('Delete this QR and its scan history? This cannot be undone.'))return;try{await api(`/api/manage/qrs/${encodeURIComponent(state.qrManageId)}`,{method:'DELETE',headers:{'x-manage-token':state.qrManageToken}});location.href='/';}catch(e){setMessage('manageMessage',e.message,'error');}}

// ---------------- Profile creator ----------------
function sanitizeSlugInput(){const el=$('profileSlug');const before=el.value;el.value=slugify(before).slice(0,40);$('slugHint').textContent=el.value?`Your link: qrajn.online/${el.value}`:'Lowercase letters, numbers and hyphens. 3–40 characters.';updateProfilePreview();}
function selectProfileTemplate(name,button){$('profileTemplate').value=name;for(const el of document.querySelectorAll('[data-profile-template]'))el.classList.toggle('active',el===button);updateProfilePreview();scheduleProfileDraft();}
function draftFields(){return ['profileSlug','profileName','profileCategory','profileTagline','profileAbout','profilePhone','profileWhatsapp','profileEmail','profileWebsite','profileAddress','profileMaps','profileHours','socialInstagram','socialFacebook','socialYoutube','socialLinkedin','socialX','socialTelegram','profileTemplate','profileAccent'];}
function scheduleProfileDraft(){clearTimeout(state.profileDraftTimer);state.profileDraftTimer=setTimeout(saveProfileDraft,280);}
function saveProfileDraft(){try{const data={};for(const id of draftFields())data[id]=$(id)?.value||'';data.customLinks=readCustomLinks('customLinksEditor');data.savedAt=Date.now();localStorage.setItem('qrajn-profile-draft-v84',JSON.stringify(data));}catch{}}
function checkProfileDraft(){try{const raw=localStorage.getItem('qrajn-profile-draft-v84');if(!raw)return;const data=JSON.parse(raw);if(!data||Date.now()-Number(data.savedAt||0)>14*86400000){clearProfileDraft();return;}$('profileDraftBanner').classList.remove('hidden');}catch{clearProfileDraft();}}
function restoreProfileDraft(){try{const data=JSON.parse(localStorage.getItem('qrajn-profile-draft-v84')||'{}');for(const id of draftFields())if($(id)&&typeof data[id]==='string')$(id).value=data[id];const host=$('customLinksEditor');host.replaceChildren();for(const item of data.customLinks||[])addCustomLinkRow('customLinksEditor',item);if(!host.children.length)addCustomLinkRow('customLinksEditor');const selected=document.querySelector(`[data-profile-template="${$('profileTemplate').value}"]`);for(const el of document.querySelectorAll('[data-profile-template]'))el.classList.toggle('active',el===selected);sanitizeSlugInput();updateProfilePreview();$('profileDraftBanner').classList.add('hidden');toast('Draft restored.','success');}catch{discardProfileDraft();}}
function discardProfileDraft(){clearProfileDraft();$('profileDraftBanner').classList.add('hidden');}
function clearProfileDraft(){try{localStorage.removeItem('qrajn-profile-draft-v84');}catch{}}
function updateProfilePreview(){const name=$('profileName').value.trim()||'Your Name';$('previewProfileName').textContent=name;$('previewCategory').textContent=$('profileCategory').value.trim()||'Your category';$('previewTagline').textContent=$('profileTagline').value.trim()||'Your short description will appear here.';$('previewAbout').textContent=$('profileAbout').value.trim()||'Add a short introduction about your profile or business.';$('previewSlug').textContent=$('profileSlug').value.trim()||'yourname';if(!state.previewLogoUrl)$('previewAvatar').textContent=initials(name);const preview=$('profileLivePreview');preview.className=`phone-preview template-${$('profileTemplate').value||'minimal'} accent-${$('profileAccent').value||'indigo'}`;}
function previewBuilderImage(kind){const input=$(kind==='logo'?'profileLogo':'profileCover');const file=input.files[0];const key=kind==='logo'?'previewLogoUrl':'previewCoverUrl';if(state[key]){URL.revokeObjectURL(state[key]);state[key]='';}const target=$(kind==='logo'?'previewAvatar':'previewCover');target.style.backgroundImage='';if(kind==='logo')target.textContent=initials($('profileName').value||'Your Name');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>4*1024*1024){setMessage('profileCreateMessage','Images must be PNG, JPEG or WebP and 4 MB or smaller.','error');input.value='';return;}state[key]=URL.createObjectURL(file);target.style.backgroundImage=`url("${state[key]}")`;target.style.backgroundSize='cover';target.style.backgroundPosition='center';if(kind==='logo')target.textContent='';}
function addCustomLinkRow(hostId,value={label:'',url:''}){const host=$(hostId);if(host.children.length>=8)return;const row=document.createElement('div');row.className='custom-link-row';const label=document.createElement('input');label.placeholder='Label';label.maxLength=60;label.value=value.label||'';label.dataset.role='label';const url=document.createElement('input');url.type='url';url.placeholder='https://...';url.value=value.url||'';url.dataset.role='url';const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove link');remove.addEventListener('click',()=>row.remove());row.append(label,url,remove);host.append(row);}
function readCustomLinks(hostId){return [...$(hostId).querySelectorAll('.custom-link-row')].map(row=>({label:row.querySelector('[data-role="label"]').value.trim(),url:row.querySelector('[data-role="url"]').value.trim()})).filter(x=>x.label&&x.url);}
function profilePayloadFromCreate(){return {slug:$('profileSlug').value,name:$('profileName').value,category:$('profileCategory').value,tagline:$('profileTagline').value,about:$('profileAbout').value,phone:$('profilePhone').value,whatsapp:$('profileWhatsapp').value,email:$('profileEmail').value,website:$('profileWebsite').value,address:$('profileAddress').value,mapsUrl:$('profileMaps').value,workingHours:$('profileHours').value,appearance:{template:$('profileTemplate').value||'minimal',accent:$('profileAccent').value||'indigo'},social:{instagram:$('socialInstagram').value,facebook:$('socialFacebook').value,youtube:$('socialYoutube').value,linkedin:$('socialLinkedin').value,x:$('socialX').value,telegram:$('socialTelegram').value},customLinks:readCustomLinks('customLinksEditor')};}
async function createProfile(e){e.preventDefault();setMessage('profileCreateMessage','Creating your public page...');const button=e.submitter||$('profileCreateForm').querySelector('button[type="submit"]');button.disabled=true;try{const r=await api('/api/profiles',{method:'POST',body:profilePayloadFromCreate()});state.createdProfile=r.profile;state.createdProfileManageUrl=r.manageUrl;const warnings=[];for(const [kind,id] of [['logo','profileLogo'],['cover','profileCover']]){const file=$(id).files[0];if(file){try{await uploadBinary(`/api/manage/profiles/${encodeURIComponent(r.profile.slug)}/media/${kind}`,file,{'x-manage-token':r.manageToken});}catch(err){warnings.push(`${kind}: ${friendlyError(err)}`);}}}clearProfileDraft();if(warnings.length){setMessage('profileCreateMessage',`Profile created, but some images were not uploaded: ${warnings.join(' | ')}`,'error');}else setMessage('profileCreateMessage','Profile created. Save the private management link.','success');await showProfileCreated(r);$('profileCreatedCard').scrollIntoView({behavior:'smooth',block:'center'});}catch(err){setMessage('profileCreateMessage',friendlyError(err),'error');}finally{button.disabled=false;}}
async function showProfileCreated(r){if(r.profile?.slug){try{const fresh=await api(`/api/profiles/${r.profile.slug}`);r.profile=fresh.profile;state.createdProfile=fresh.profile;}catch{}}$('createdPublicUrl').value=r.publicUrl;$('createdManageUrl').value=r.manageUrl;$('openCreatedPublic').href=r.publicUrl;$('openCreatedManage').href=r.manageUrl;renderQrInto('profileCreatedQr',r.profileQrUrl,272);$('profileCreatedCard').classList.remove('hidden');}
function downloadCreatedProfileQr(){if(!state.createdProfile)return;downloadCanvasFromHost('profileCreatedQr',`${safeFilename(state.createdProfile.slug)}-profile-qr.png`);}

// ---------------- Public profile ----------------
async function showPublicProfile(slug){$('publicProfileView').classList.remove('hidden');$('publicProfileCard').classList.add('hidden');$('publicProfileError').classList.add('hidden');try{const {profile}=await api(`/api/profiles/${encodeURIComponent(slug)}`);state.publicProfile=profile;renderPublicProfile(profile);$('publicProfileCard').classList.remove('hidden');document.title=`${profile.name} · QR AJN`;}catch(e){$('publicProfileError').textContent=e.message||'Profile not found';$('publicProfileError').classList.remove('hidden');}}
function renderPublicProfile(p){const appearance=p.appearance||{template:'minimal',accent:'indigo'};const card=$('publicProfileCard');card.className=`public-profile-card template-${appearance.template||'minimal'} accent-${appearance.accent||'indigo'}`;const cover=$('publicCover');cover.style.backgroundImage=p.media.cover?`url("${cssUrl(p.media.cover)}")`:'';const logo=$('publicLogo');logo.style.backgroundImage=p.media.logo?`url("${cssUrl(p.media.logo)}")`:'';logo.textContent=p.media.logo?'':initials(p.name);$('publicName').textContent=p.name;$('publicCategory').textContent=p.category||'Public profile';$('publicTagline').textContent=p.tagline||'';$('publicAbout').textContent=p.about||'';$('publicAboutSection').classList.toggle('hidden',!p.about);renderPublicActions(p);renderPublicDetails(p);renderPublicLinks(p);renderPublicDocuments(p);renderQrInto('publicQr',p.profileQrUrl,248);}
function renderPublicActions(p){const host=$('publicPrimaryActions');host.replaceChildren();const add=(label,href,action,primary=false)=>{if(!href)return;const a=document.createElement('a');a.className=`profile-action${primary?' primary':''}`;a.textContent=label;a.href=href;a.target=href.startsWith('http')?'_blank':'';if(a.target)a.rel='noopener';a.addEventListener('click',()=>logProfileAction(action,label));host.append(a);};add('WhatsApp',p.whatsapp?`https://wa.me/${phoneClean(p.whatsapp).replace(/^\+/,'')}`:'','whatsapp',true);add('Call',p.phone?`tel:${phoneClean(p.phone)}`:'','call');add('Email',p.email?`mailto:${p.email}`:'','email');add('Website',p.website,'website');add('Location',p.mapsUrl,'location');}
function renderPublicDetails(p){const host=$('publicDetails');host.replaceChildren();const rows=[['Phone',p.phone],['Email',p.email],['Address',p.address],['Working hours',p.workingHours]];for(const [label,value] of rows){if(!value)continue;const row=document.createElement('div');row.className='detail-item';const b=document.createElement('b');b.textContent=label;const span=document.createElement('span');span.textContent=value;row.append(b,span);host.append(row);}$('publicDetailsSection').classList.toggle('hidden',!host.children.length);}
function renderPublicLinks(p){const host=$('publicSocials');host.replaceChildren();const labels={instagram:'Instagram',facebook:'Facebook',youtube:'YouTube',linkedin:'LinkedIn',x:'X / Twitter',telegram:'Telegram'};for(const [key,label] of Object.entries(labels)){if(!p.social?.[key])continue;host.append(linkCard(label,p.social[key],key));}for(const item of p.customLinks||[])host.append(linkCard(item.label,item.url,'custom-link'));$('publicSocialSection').classList.toggle('hidden',!host.children.length);}
function linkCard(label,url,action){const a=document.createElement('a');a.className='profile-link';a.href=url;a.target='_blank';a.rel='noopener';const span=document.createElement('span');span.textContent=label;const arrow=document.createElement('b');arrow.textContent='↗';a.append(span,arrow);a.addEventListener('click',()=>logProfileAction(action,label));return a;}
function renderPublicDocuments(p){const host=$('publicDocuments');host.replaceChildren();for(const d of p.documents||[]){const card=document.createElement('div');card.className='document-card';const icon=document.createElement('div');icon.className='document-icon';icon.textContent='PDF';const meta=document.createElement('div');const strong=document.createElement('strong');strong.textContent=d.title;const small=document.createElement('small');small.textContent=`${formatBytes(d.size)} · /${p.slug}/${d.slug}`;meta.append(strong,small);const acts=document.createElement('div');acts.className='document-actions';const view=document.createElement('a');view.textContent='View';view.href=d.url;view.target='_blank';view.rel='noopener';const share=document.createElement('button');share.type='button';share.textContent='Share';share.addEventListener('click',()=>shareDocument(p,d));acts.append(view,share);card.append(icon,meta,acts);host.append(card);}$('publicDocumentsSection').classList.toggle('hidden',!host.children.length);}
async function shareDocument(p,d){try{await fetch(`/api/profiles/${encodeURIComponent(p.slug)}/documents/${encodeURIComponent(d.slug)}/share`,{method:'POST'});}catch{}if(navigator.share){try{await navigator.share({title:d.title,text:`${d.title} · ${p.name}`,url:d.url});return;}catch{}}await copyText(d.url);}
async function logProfileAction(action,label){if(!state.publicProfile)return;fetch(`/api/profiles/${encodeURIComponent(state.publicProfile.slug)}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,label})}).catch(()=>{});}
async function sharePublicProfile(){const p=state.publicProfile;if(!p)return;logProfileAction('share-profile','Share profile');if(navigator.share){try{await navigator.share({title:p.name,text:p.tagline||p.name,url:p.publicUrl});return;}catch{}}await copyText(p.publicUrl);}
async function copyCurrentPublicProfile(){if(!state.publicProfile)return;logProfileAction('copy-profile','Copy profile');await copyText(state.publicProfile.publicUrl);}
function downloadPublicProfileQr(){if(!state.publicProfile)return;downloadCanvasFromHost('publicQr',`${safeFilename(state.publicProfile.slug)}-profile-qr.png`);}

// ---------------- Profile management ----------------
async function showProfileManage(slug,token){state.profileManageSlug=slug;state.profileManageToken=token;$('profileManageView').classList.remove('hidden');document.title='Profile Analytics · QR AJN';await refreshProfileManage(true);startSmartRefresh(()=>refreshProfileManage(false));}
async function refreshProfileManage(first){try{const data=await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}`,{headers:{'x-manage-token':state.profileManageToken}});state.currentManagedProfile=data;renderProfileManage(data,first);$('profileManageError').classList.add('hidden');$('profileManageContent').classList.remove('hidden');$('profileManageLiveText').textContent='Live · updated just now';}catch(e){$('profileManageLiveText').textContent='Connection interrupted · retrying';if(first){$('profileManageContent').classList.add('hidden');$('profileManageError').textContent=friendlyError(e);$('profileManageError').classList.remove('hidden');}}}
function renderProfileManage(data,fillEditor=false){const p=data.profile,m=data.metrics;$('profileManageHeading').textContent='Profile analytics';$('profileManageSubheading').textContent=`Private management · qrajn.online/${p.slug}`;$('profileManageName').textContent=p.name;$('profileManagePublicLink').textContent=p.publicUrl;$('profileManagePublicLink').href=p.publicUrl;$('profileActiveToggle').checked=p.isActive;$('profileActiveLabel').textContent=p.isActive?'Active':'Paused';$('fixedProfileSlug').textContent=`/${p.slug}`;$('previewManagedProfile').href=p.publicUrl;renderQrInto('profileManageQr',p.profileQrUrl,248);setMetricValue('pmScans',m.qrScans.total,fillEditor);$('pmScansSub').textContent=`${formatNumber(m.qrScans.today)} today · ${formatNumber(m.qrScans.last30)} in 30 days`;setMetricValue('pmViews',m.profileViews.total,fillEditor);$('pmViewsSub').textContent=`${formatNumber(m.profileViews.today)} today · ${formatNumber(m.profileViews.last30)} in 30 days`;setMetricValue('pmClicks',m.totalActions,fillEditor);setMetricValue('pmPdfViews',m.documentViews,fillEditor);setMetricValue('pmUnique',m.uniqueApprox,fillEditor);renderProfileChart(data.daily);renderBreakdown('profileTopActions',data.topActions,'No actions yet.');renderBreakdown('profileDeviceBreakdown',data.devices,'No visitor data yet.');renderBreakdown('profileBrowserBreakdown',data.browsers||[],'No browser data yet.');renderProfileRecent(data.recent);if(fillEditor)fillProfileEdit(p);renderManagedMedia(p);renderManagedDocuments(data.documents,p);}
function fillProfileEdit(p){const map={editProfileName:p.name,editProfileCategory:p.category,editProfileTagline:p.tagline,editProfileAbout:p.about,editProfilePhone:p.phone,editProfileWhatsapp:p.whatsapp,editProfileEmail:p.email,editProfileWebsite:p.website,editProfileAddress:p.address,editProfileMaps:p.mapsUrl,editProfileHours:p.workingHours,editSocialInstagram:p.social?.instagram,editSocialFacebook:p.social?.facebook,editSocialYoutube:p.social?.youtube,editSocialLinkedin:p.social?.linkedin,editSocialX:p.social?.x,editSocialTelegram:p.social?.telegram,editProfileTemplate:p.appearance?.template||'minimal',editProfileAccent:p.appearance?.accent||'indigo'};for(const [id,v] of Object.entries(map))$(id).value=v||'';const host=$('editCustomLinksEditor');host.replaceChildren();for(const item of p.customLinks||[])addCustomLinkRow('editCustomLinksEditor',item);if(!host.children.length)addCustomLinkRow('editCustomLinksEditor');state.profileDirty=false;$('profileUnsavedBadge').classList.add('hidden');}
function managedProfilePatch(){return {name:$('editProfileName').value,category:$('editProfileCategory').value,tagline:$('editProfileTagline').value,about:$('editProfileAbout').value,phone:$('editProfilePhone').value,whatsapp:$('editProfileWhatsapp').value,email:$('editProfileEmail').value,website:$('editProfileWebsite').value,address:$('editProfileAddress').value,mapsUrl:$('editProfileMaps').value,workingHours:$('editProfileHours').value,appearance:{template:$('editProfileTemplate').value||'minimal',accent:$('editProfileAccent').value||'indigo'},social:{instagram:$('editSocialInstagram').value,facebook:$('editSocialFacebook').value,youtube:$('editSocialYoutube').value,linkedin:$('editSocialLinkedin').value,x:$('editSocialX').value,telegram:$('editSocialTelegram').value},customLinks:readCustomLinks('editCustomLinksEditor')};}
async function saveManagedProfile(e){e.preventDefault();try{await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}`,{method:'PATCH',headers:{'x-manage-token':state.profileManageToken},body:managedProfilePatch()});state.profileDirty=false;$('profileUnsavedBadge').classList.add('hidden');setMessage('profileEditMessage','Profile updated. Public URL and QR remain unchanged.','success');toast('Profile updated.','success');await refreshProfileManage(false);}catch(err){setMessage('profileEditMessage',friendlyError(err),'error');}}
async function toggleManagedProfile(){try{await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}`,{method:'PATCH',headers:{'x-manage-token':state.profileManageToken},body:{isActive:$('profileActiveToggle').checked}});await refreshProfileManage(false);}catch(e){$('profileActiveToggle').checked=!$('profileActiveToggle').checked;setMessage('profileEditMessage',e.message,'error');}}
function renderManagedMedia(p){for(const [kind,id] of [['logo','managedLogoPreview'],['cover','managedCoverPreview']]){const el=$(id);const url=p.media?.[kind];el.style.backgroundImage=url?`url("${cssUrl(url)}")`:'';el.textContent=url?'':`No ${kind}`;}}
async function uploadManagedMedia(kind){const input=$(kind==='logo'?'managedLogoFile':'managedCoverFile');const file=input.files[0];if(!file){setMessage('mediaMessage',`Choose a ${kind} image first.`,'error');return;}if(file.size>4*1024*1024){setMessage('mediaMessage','Image must be 4 MB or smaller.','error');return;}try{await uploadBinary(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}/media/${kind}`,file,{'x-manage-token':state.profileManageToken});setMessage('mediaMessage',`${kind==='logo'?'Logo':'Cover'} updated.`,'success');input.value='';await refreshProfileManage(false);}catch(e){setMessage('mediaMessage',e.message,'error');}}
async function removeManagedMedia(kind){try{await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}/media/${kind}`,{method:'DELETE',headers:{'x-manage-token':state.profileManageToken}});setMessage('mediaMessage',`${kind==='logo'?'Logo':'Cover'} removed.`,'success');await refreshProfileManage(false);}catch(e){setMessage('mediaMessage',e.message,'error');}}
async function uploadManagedDocument(e){e.preventDefault();const title=$('documentTitle').value.trim();const slug=slugify($('documentSlug').value||title).slice(0,60);const file=$('documentFile').files[0];if(!title||!slug||!file){setMessage('documentMessage','Enter a title, link name and choose a PDF.','error');return;}if(file.type!=='application/pdf'){setMessage('documentMessage','Choose a PDF file.','error');return;}if(file.size>12*1024*1024){setMessage('documentMessage','PDF must be 12 MB or smaller.','error');return;}try{await uploadBinary(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}/documents`,file,{'x-manage-token':state.profileManageToken,'x-document-title':title,'x-document-slug':slug});setMessage('documentMessage','PDF uploaded with a clean public link.','success');e.target.reset();$('documentSlug').dataset.touched='';await refreshProfileManage(false);}catch(err){setMessage('documentMessage',err.message,'error');}}
function renderManagedDocuments(docs,p){const host=$('managedDocuments');host.replaceChildren();if(!docs.length){host.innerHTML='<div class="empty-mini">No PDFs yet. Upload a brochure, menu, resume, price list or other public document.</div>';return;}for(const d of docs){const row=document.createElement('div');row.className='managed-document';const icon=document.createElement('div');icon.className='document-icon';icon.textContent='PDF';const meta=document.createElement('div');const strong=document.createElement('strong');strong.textContent=d.title;const small=document.createElement('div');small.className='stats';small.textContent=`/${p.slug}/${d.slug} · ${formatNumber(d.views)} views · ${formatNumber(d.shares)} shares · ${formatBytes(d.size)}`;meta.append(strong,small);const acts=document.createElement('div');acts.className='inline-actions';const open=document.createElement('a');open.className='button secondary';open.href=d.url;open.target='_blank';open.rel='noopener';open.textContent='Open';const copy=document.createElement('button');copy.className='button secondary';copy.type='button';copy.textContent='Copy link';copy.addEventListener('click',()=>copyText(d.url));const del=document.createElement('button');del.className='button danger';del.type='button';del.textContent='Delete';del.addEventListener('click',()=>deleteManagedDocument(d));acts.append(open,copy,del);row.append(icon,meta,acts);host.append(row);}}
async function deleteManagedDocument(d){if(!confirm(`Delete “${d.title}”? Its clean public link will stop working.`))return;try{await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}/documents/${encodeURIComponent(d.slug)}`,{method:'DELETE',headers:{'x-manage-token':state.profileManageToken}});setMessage('documentMessage','PDF deleted.','success');await refreshProfileManage(false);}catch(e){setMessage('documentMessage',e.message,'error');}}
function renderProfileRecent(items){const host=$('profileRecent');host.replaceChildren();if(!items.length){host.innerHTML='<div class="empty-mini">No activity yet.</div>';return;}const labels={qr_scan:'QR scan',profile_view:'Profile view',action:'Action',document_view:'PDF view',document_share:'PDF share'};for(const e of items){const row=document.createElement('div');row.className='recent-row';const icon=document.createElement('span');icon.className='recent-icon';icon.textContent=e.type==='qr_scan'?'QR':e.type==='profile_view'?'VIEW':e.type.startsWith('document')?'PDF':'ACT';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=`${labels[e.type]||e.type}${e.action?` · ${titleCase(e.action)}`:''}${e.label?` · ${e.label}`:''}`;const sub=document.createElement('small');sub.textContent=`${e.device} · ${e.browser} · ${e.os}${e.isBot?' · automated':''}`;info.append(title,sub);const time=document.createElement('time');time.textContent=formatRelative(e.createdAt);row.append(icon,info,time);host.append(row);}}
function setProfileChartMode(mode){state.profileChartMode=mode;for(const [id,key] of [['profileChartScans','scans'],['profileChartViews','views'],['profileChartActions','clicks']])$(id).classList.toggle('active',key===mode);if(state.currentManagedProfile)renderProfileChart(state.currentManagedProfile.daily);}
function renderProfileChart(items){const labels={scans:'Scans',views:'Views',clicks:'Actions'};renderLineChart('profileDailyChart',filterDaily(items,state.profileChartRange),state.profileChartMode,labels[state.profileChartMode]||'Activity');}
function filterDaily(items,days){const list=Array.isArray(items)?items:[];return list.slice(-Math.max(1,Number(days)||30));}
function setAnalyticsRange(kind,days){const prefix=kind==='qr'?'qrRange':'profileRange';const ids=[[`${prefix}Today`,1],[`${prefix}7`,7],[`${prefix}30`,30]];for(const [id,n] of ids)$(id)?.classList.toggle('active',n===days);if(kind==='qr'){state.qrChartRange=days;$('qrRangeLabel').textContent=days===1?'TODAY':`${days} DAYS`;if(state.currentManagedQr)renderLineChart('dailyChart',filterDaily(state.currentManagedQr.daily,days),'count','Scans');}else{state.profileChartRange=days;$('profileRangeLabel').textContent=days===1?'TODAY':`${days} DAYS`;if(state.currentManagedProfile)renderProfileChart(state.currentManagedProfile.daily);}}
function cleanFrameText(v){return String(v||'SCAN ME').replace(/[\u0000-\u001f<>]/g,'').trim().slice(0,24)||'SCAN ME';}
function svgEscape(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function markProfileDirty(){state.profileDirty=true;$('profileUnsavedBadge').classList.remove('hidden');}
async function shareManagedProfile(){const p=state.currentManagedProfile?.profile;if(!p)return;if(navigator.share){try{await navigator.share({title:p.name,text:p.tagline||p.name,url:p.publicUrl});return;}catch{}}await copyText(p.publicUrl);}
function downloadManagedProfileQr(){const p=state.currentManagedProfile?.profile;if(!p)return;downloadCanvasFromHost('profileManageQr',`${safeFilename(p.slug)}-profile-qr.png`);}
async function deleteManagedProfile(){if(!confirm('Delete this profile, its local analytics, images and PDFs? This cannot be undone.'))return;try{await api(`/api/manage/profiles/${encodeURIComponent(state.profileManageSlug)}`,{method:'DELETE',headers:{'x-manage-token':state.profileManageToken}});location.href='/';}catch(e){setMessage('profileEditMessage',e.message,'error');}}

// ---------------- Shared UI helpers ----------------
function openPastedManageLink(e){e.preventDefault();const value=$('manageLinkInput').value.trim();try{const u=new URL(value);if(!parseQrManageRoute(u.pathname)&&!parseProfileManageRoute(u.pathname))throw new Error('That is not a valid QR AJN private management link.');location.href=u.href;}catch(err){setMessage('manageDialogMessage',err.message,'error');}}
function parseQrManageRoute(p){const m=String(p).match(/^\/manage\/([A-Za-z0-9_-]{6,100})\/([A-Za-z0-9_-]{20,200})\/?$/);return m?{id:m[1],token:m[2]}:null;}
function parseProfileManageRoute(p){const m=String(p).match(/^\/manage\/profile\/([a-z0-9-]{3,40})\/([A-Za-z0-9_-]{20,200})\/?$/);return m?{slug:m[1],token:m[2]}:null;}
function clearRefresh(){if(state.refreshTimer){clearTimeout(state.refreshTimer);state.refreshTimer=null;}state.refreshHandler=null;}
function renderQrInto(hostId,payload,size=248){const matrix=createQrMatrix(payload,{level:'M'});const canvas=document.createElement('canvas');drawMatrixToCanvas(canvas,matrix.matrix,{size,margin:4,foreground:'#0f172a',background:'#ffffff',style:'square'});$(hostId).replaceChildren(canvas);return canvas;}
function startSmartRefresh(fn){clearRefresh();state.refreshHandler=fn;const schedule=()=>{const delay=document.hidden?30000:5000;state.refreshTimer=setTimeout(async()=>{if(!state.refreshHandler)return;try{await state.refreshHandler();}finally{if(state.refreshHandler)schedule();}},delay);};schedule();}
async function handleVisibilityChange(){if(!document.hidden&&state.refreshHandler){clearTimeout(state.refreshTimer);state.refreshTimer=null;try{await state.refreshHandler();}finally{if(state.refreshHandler)startSmartRefresh(state.refreshHandler);}}}
function setMetricValue(id,value,initial=false){const el=$(id);if(!el)return;const next=formatNumber(value);if(el.textContent===next)return;el.textContent=next;el.classList.remove('metric-animate');void el.offsetWidth;el.classList.add('metric-animate');setTimeout(()=>el.classList.remove('metric-animate'),350);}
function renderLineChart(hostId,items,key,label){const host=$(hostId);host.replaceChildren();const data=(items||[]).map(x=>({date:x.date,value:Number(x[key]||0)}));if(!data.length||!data.some(x=>x.value>0)){host.innerHTML=`<div class="line-chart-empty"><div><strong>No ${String(label||'activity').toLowerCase()} yet</strong><br><span>Real activity will appear here automatically.</span></div></div>`;return;}const w=760,h=250,pad={l:34,r:16,t:18,b:30};const innerW=w-pad.l-pad.r,innerH=h-pad.t-pad.b;const max=Math.max(1,...data.map(x=>x.value));const x=i=>pad.l+(data.length===1?innerW/2:(i/(data.length-1))*innerW);const y=v=>pad.t+innerH-(v/max)*innerH;const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`${label} over time`);for(let i=0;i<4;i++){const gy=pad.t+(innerH/3)*i;const line=document.createElementNS(ns,'line');line.setAttribute('x1',pad.l);line.setAttribute('x2',w-pad.r);line.setAttribute('y1',gy);line.setAttribute('y2',gy);line.setAttribute('class','grid-line');svg.append(line);const text=document.createElementNS(ns,'text');text.setAttribute('x',3);text.setAttribute('y',gy+3);text.setAttribute('class','axis-label');text.textContent=Math.round(max-(max/3)*i);svg.append(text);}const pts=data.map((d,i)=>[x(i),y(d.value)]);const area=document.createElementNS(ns,'path');const areaD=`M ${pts[0][0]} ${pad.t+innerH} L ${pts.map(p=>`${p[0]} ${p[1]}`).join(' L ')} L ${pts[pts.length-1][0]} ${pad.t+innerH} Z`;area.setAttribute('d',areaD);area.setAttribute('class','trend-area');svg.append(area);const path=document.createElementNS(ns,'path');path.setAttribute('d',`M ${pts.map(p=>`${p[0]} ${p[1]}`).join(' L ')}`);path.setAttribute('class','trend-line');svg.append(path);for(let i=0;i<pts.length;i++){const [px,py]=pts[i];const c=document.createElementNS(ns,'circle');c.setAttribute('cx',px);c.setAttribute('cy',py);c.setAttribute('r','3.4');c.setAttribute('class','trend-dot');const title=document.createElementNS(ns,'title');title.textContent=`${data[i].date}: ${data[i].value} ${String(label||'').toLowerCase()}`;c.append(title);svg.append(c);if(i===0||i===pts.length-1||i===Math.floor((pts.length-1)/2)){const t=document.createElementNS(ns,'text');t.setAttribute('x',px);t.setAttribute('y',h-7);t.setAttribute('text-anchor',i===0?'start':i===pts.length-1?'end':'middle');t.setAttribute('class','axis-label');t.textContent=data[i].date.slice(5);svg.append(t);}}host.append(svg);}
function toast(message,type=''){const host=$('toastRegion');if(!host)return;const el=document.createElement('div');el.className=`toast ${type}`.trim();el.textContent=message;host.append(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateY(8px)';setTimeout(()=>el.remove(),180);},2200);}
function friendlyError(err){const text=String(err?.message||err||'Something went wrong.');if(/SQLITE|ECONN|ENOTFOUND|EPIPE|stack|syntax/i.test(text))return'Unable to complete that action. Please try again.';return text;}
function renderSimpleChart(hostId,items){renderLineChart(hostId,items,'count','Scans');}
function renderBreakdown(hostId,items,empty='No activity yet.'){const host=$(hostId);host.replaceChildren();const total=items.reduce((s,x)=>s+x.count,0);if(!total){host.innerHTML=`<div class="empty-mini">${empty}</div>`;return;}for(const item of items){const row=document.createElement('div');row.className='breakdown-row';const label=document.createElement('span');label.textContent=titleCase(item.label);const progress=document.createElement('div');progress.className='progress';const fill=document.createElement('i');fill.style.width=`${Math.round(item.count/total*100)}%`;progress.append(fill);const count=document.createElement('b');count.textContent=item.count;row.append(label,progress,count);host.append(row);}}
function downloadCanvasFromHost(hostId,name){const canvas=$(hostId).querySelector('canvas');if(!canvas)return;canvas.toBlob(b=>downloadBlob(b,name),'image/png');}
function downloadBlob(blob,name){if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function api(url,{method='GET',headers={},body}={}){const opts={method,headers:{...headers}};if(body!==undefined){opts.headers['content-type']='application/json';opts.body=JSON.stringify(body);}const r=await fetch(url,opts);let data={};try{data=await r.json();}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data;}
async function uploadBinary(url,file,headers={}){const method=/\/media\/(logo|cover)$/.test(url)?'PUT':'POST';const r=await fetch(url,{method,headers:{...headers,'content-type':file.type||'application/octet-stream'},body:file});let data={};try{data=await r.json();}catch{}if(!r.ok)throw new Error(data.error||`Upload failed (${r.status})`);return data;}

function requireHttpUrl(raw){const value=String(raw||'').trim();let u;try{u=new URL(value);}catch{throw new Error('Enter a complete URL beginning with http:// or https://.');}if(!['http:','https:'].includes(u.protocol))throw new Error('Only http:// and https:// URLs are supported.');if(u.username||u.password)throw new Error('URLs with embedded usernames or passwords are not allowed.');return u.href;}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;}function phoneClean(v){return String(v||'').replace(/[^\d+*#;,]/g,'').slice(0,40);}function wifiEscape(v){return String(v||'').replace(/([\\;,:"])/g,'\\$1');}function vcard(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/([;,])/g,'\\$1');}function safeFilename(v){return String(v||'qr-ajn').toLowerCase().replace(/[^a-z0-9-_]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'qr-ajn';}function slugify(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'').replace(/-+/g,'-').replace(/^-|-$/g,'');}
function initials(v){const parts=String(v||'QR AJN').trim().split(/\s+/).filter(Boolean);return (parts.slice(0,2).map(x=>x[0]).join('')||'QA').toUpperCase();}function formatNumber(v){return new Intl.NumberFormat().format(Number(v||0));}function formatDate(v){return new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});}function formatRelative(v){const s=Math.max(0,Math.round((Date.now()-Date.parse(v))/1000));if(s<10)return'now';if(s<60)return`${s}s`;if(s<3600)return`${Math.floor(s/60)}m`;if(s<86400)return`${Math.floor(s/3600)}h`;return`${Math.floor(s/86400)}d`;}function formatBytes(n){const v=Number(n||0);if(v<1024)return`${v} B`;if(v<1024*1024)return`${(v/1024).toFixed(1)} KB`;return`${(v/1024/1024).toFixed(1)} MB`;}function titleCase(v){return String(v||'').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
async function copyText(text){try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}toast('Copied to clipboard.','success');}
function setMessage(id,text,type=''){const el=$(id);if(!el)return;el.textContent=text;el.className=`message ${type}`.trim();}function cssUrl(v){return String(v||'').replace(/["'()\\\n\r]/g,'');}
