import fs from 'node:fs/promises';
import fssync from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

export function createV9Extra({root,dataDir,firestore=null,storageBucket=null,isVercel=Boolean(process.env.VERCEL)}){
  const file=process.env.QR_AJN_V9_DATA_FILE?path.resolve(process.env.QR_AJN_V9_DATA_FILE):path.join(dataDir,'v9-extra.json');
  const uploadDir=process.env.QR_AJN_V9_UPLOAD_DIR?path.resolve(process.env.QR_AJN_V9_UPLOAD_DIR):path.join(dataDir,'v9-uploads');
  let queue=Promise.resolve();
  const rates=new Map();
  const RESERVED=new Set(['api','manage','login','signup','privacy','terms','contact','about','analytics','assets','public','r','create','profile','profiles','qr','qrs','media','favicon','robots','sitemap','ads','health','index','404','manifest','static','dashboard','workspace','account','pricing','premium','billing','smartcreate','smarttools','v9analytics','v9pdfeditor','v9items']);

  const empty=()=>({links:{},campaigns:{},documents:{},files:{},events:{},publicLinks:{},system:{createdAt:new Date().toISOString(),installSecret:crypto.randomBytes(32).toString('hex')}});
  const normalize=db=>{db=db&&typeof db==='object'?db:empty();for(const k of ['links','campaigns','documents','files','events','publicLinks'])db[k]=db[k]&&typeof db[k]==='object'?db[k]:{};db.system=db.system&&typeof db.system==='object'?db.system:{};if(!db.system.installSecret)db.system.installSecret=crypto.randomBytes(32).toString('hex');if(!db.system.createdAt)db.system.createdAt=new Date().toISOString();return db};
  const clean=v=>JSON.parse(JSON.stringify(v));
  const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  const init=async()=>{if(firestore){const ref=firestore.collection('system').doc('runtime');const snap=await ref.get();if(!snap.exists)await ref.create({schema:4,installSecret:crypto.randomBytes(32).toString('hex'),updatedAt:new Date().toISOString()});else if(!snap.data()?.installSecret)await ref.set({installSecret:crypto.randomBytes(32).toString('hex'),updatedAt:new Date().toISOString()},{merge:true});return;}if(isVercel)return;await fs.mkdir(path.dirname(file),{recursive:true});await fs.mkdir(uploadDir,{recursive:true});if(!fssync.existsSync(file))await fs.writeFile(file,JSON.stringify(empty(),null,2));};
  const ready=init();
  const readFirestore=async(reader=null)=>{const get=ref=>reader?reader.get(ref):ref.get();const [runtime,links,campaigns,documents,files,events,publicLinks]=await Promise.all([get(firestore.collection('system').doc('runtime')),get(firestore.collection('v9Links')),get(firestore.collection('v9Campaigns')),get(firestore.collection('v9Documents')),get(firestore.collection('v9Files')),get(firestore.collection('v9Events')),get(firestore.collection('publicLinks'))]);const toMap=snap=>Object.fromEntries(snap.docs.map(d=>[d.id,d.data()]));return normalize({links:toMap(links),campaigns:toMap(campaigns),documents:toMap(documents),files:toMap(files),events:toMap(events),publicLinks:toMap(publicLinks),system:{...(runtime.exists?runtime.data():{}),createdAt:runtime.data()?.createdAt||new Date().toISOString()}})};
  const read=async()=>{await ready;if(firestore)return readFirestore();if(isVercel){const e=new Error('Cloud Firestore is not configured for QR AJN.');e.status=503;throw e}try{return normalize(JSON.parse(await fs.readFile(file,'utf8')))}catch{return normalize(empty())}};
  const syncMap=(tx,collection,before,after,{deleteFilter=null}={})=>{const col=firestore.collection(collection);for(const [id,item] of Object.entries(after||{}))if(!(id in (before||{}))||!same(before[id],item))tx.set(col.doc(id),clean(item));for(const id of Object.keys(before||{}))if(!(id in (after||{}))&&(!deleteFilter||deleteFilter(before[id])))tx.delete(col.doc(id));};
  const mutate=fn=>{if(firestore)return firestore.runTransaction(async tx=>{const current=await readFirestore(tx),before=structuredClone(current),result=await fn(current);const after=normalize(current);tx.set(firestore.collection('system').doc('runtime'),{installSecret:after.system.installSecret,updatedAt:new Date().toISOString()},{merge:true});syncMap(tx,'v9Links',before.links,after.links);syncMap(tx,'v9Campaigns',before.campaigns,after.campaigns);syncMap(tx,'v9Documents',before.documents,after.documents);syncMap(tx,'v9Files',before.files,after.files);syncMap(tx,'v9Events',before.events,after.events);syncMap(tx,'publicLinks',before.publicLinks,after.publicLinks,{deleteFilter:x=>String(x?.type||'').startsWith('v9-')||['links','documents'].includes(String(x?.type||''))});return result});if(isVercel){const e=new Error('Cloud Firestore is not configured for QR AJN.');e.status=503;throw e}const run=queue.then(async()=>{const db=await read();const result=await fn(db);await fs.writeFile(file,JSON.stringify(db,null,2));return result;});queue=run.catch(()=>{});return run;};
  const text=(v,n=200)=>String(v??'').trim().slice(0,n);
  const now=()=>new Date().toISOString();
  const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
  const token=()=>crypto.randomBytes(24).toString('base64url');
  const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
  const validUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)}catch{return false}};
  const slugify=v=>text(v,60).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,48);
  const validSlug=s=>/^[a-z0-9][a-z0-9-]{1,46}[a-z0-9]$/.test(s)&&!RESERVED.has(s);
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ip=req=>text(String(req.headers['x-forwarded-for']||'').split(',')[0]||req.socket.remoteAddress||'unknown',100);
  const uaInfo=ua=>{const s=String(ua||'').toLowerCase();return{device:/(mobile|iphone|android)/.test(s)?'Mobile':/(ipad|tablet)/.test(s)?'Tablet':'Desktop',browser:/edg\//.test(s)?'Edge':/chrome\//.test(s)?'Chrome':/firefox\//.test(s)?'Firefox':/safari\//.test(s)&&!/chrome/.test(s)?'Safari':'Other',os:/android/.test(s)?'Android':/(iphone|ipad|ios)/.test(s)?'iOS':/windows/.test(s)?'Windows':/mac os|macintosh/.test(s)?'macOS':/linux/.test(s)?'Linux':'Other'};};
  const isBot=req=>/(bot|crawler|spider|preview|headless|lighthouse|facebookexternalhit|slackbot|discordbot|telegrambot|whatsapp)/i.test(String(req.headers['user-agent']||''));
  const visitor=(req,secret)=>crypto.createHmac('sha256',secret).update(`${ip(req)}|${req.headers['user-agent']||''}`).digest('hex').slice(0,24);
  const headers=(res,extra={})=>{for(const [k,v] of Object.entries({'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Cache-Control':'no-store',...extra}))res.setHeader(k,v)};
  const json=(res,status,obj)=>{headers(res,{'Content-Type':'application/json; charset=utf-8'});res.writeHead(status);res.end(JSON.stringify(obj));};
  const html=(res,status,body,noindex=false)=>{headers(res,{'Content-Type':'text/html; charset=utf-8'});if(noindex)res.setHeader('X-Robots-Tag','noindex, nofollow');res.writeHead(status);res.end(body);};
  const redirect=(res,url)=>{headers(res,{Location:url});res.writeHead(302);res.end();};
  const body=async(req,max=1024*1024)=>{let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>max){const e=new Error('Request too large');e.status=413;throw e}chunks.push(c)}return Buffer.concat(chunks)};
  const readJson=async req=>{const b=await body(req);if(!b.length)return{};try{return JSON.parse(b.toString('utf8'))}catch{const e=new Error('Invalid JSON');e.status=400;throw e}};
  const rate=(req,key,limit=120)=>{const k=`${key}:${ip(req)}`,t=Date.now(),arr=(rates.get(k)||[]).filter(x=>t-x<60000);arr.push(t);rates.set(k,arr);return arr.length<=limit};
  const originSafe=o=>String(o||'').replace(/\/$/,'');
  const withUtm=(dest,utm={})=>{if(!validUrl(dest))return dest;const u=new URL(dest);for(const [k,v]of Object.entries({utm_source:utm.source,utm_medium:utm.medium,utm_campaign:utm.campaign,utm_term:utm.term,utm_content:utm.content}))if(text(v,120))u.searchParams.set(k,text(v,120));return u.toString()};
  const installSecret=async()=>{if(firestore){const snap=await firestore.collection('system').doc('runtime').get();return String(snap.data()?.installSecret||'')}return (await read()).system.installSecret};
  const record=async(req,type,resourceType,resourceId,action='')=>{const info=uaInfo(req.headers['user-agent']);const e={id:id('evt'),type,resourceType,resourceId,action:text(action,100),createdAt:now(),visitorHash:visitor(req,await installSecret()),referrer:text(req.headers.referer,300),isBot:isBot(req),...info};if(firestore){await firestore.collection('v9Events').doc(e.id).set(clean(e));return e}return mutate(db=>{db.events[e.id]=e;return e})};
  const oldDb=async()=>{if(firestore){const [scans,events]=await Promise.all([firestore.collectionGroup('scans').get(),firestore.collectionGroup('events').get()]);return{qrs:[],profiles:[],scans:scans.docs.map(d=>d.data()),profileEvents:events.docs.map(d=>d.data())}}try{return JSON.parse(await fs.readFile(path.join(dataDir,'local-db.json'),'utf8'))}catch{return{qrs:[],profiles:[],scans:[],profileEvents:[]}}};
  const reserve=async(slug,ref)=>{if(!validSlug(slug)){const e=new Error('Use 3–48 lowercase letters, numbers or hyphens for the public name.');e.status=400;throw e}if(firestore)return firestore.runTransaction(async tx=>{const r=firestore.collection('publicLinks').doc(slug),snap=await tx.get(r);if(snap.exists){const e=new Error('That public name is already taken.');e.status=409;throw e}tx.set(r,{type:ref.type==='links'?'links':'documents',resourceId:ref.id,active:true,updatedAt:now(),createdAt:ref.createdAt||now()});});const legacy=await oldDb();if((legacy.profiles||[]).some(x=>x.slug===slug)){const e=new Error('That public name is already used by a profile.');e.status=409;throw e}return mutate(db=>{if(db.publicLinks[slug]){const e=new Error('That public name is already taken.');e.status=409;throw e}db.publicLinks[slug]=ref;});};
  const shortCode=(length=6)=>{const chars='abcdefghjkmnpqrstuvwxyz23456789';let out='';for(let i=0;i<length;i++)out+=chars[crypto.randomInt(0,chars.length)];return out;};
  const reserveLinkSlug=async(preferred,ref)=>{const requested=slugify(preferred);if(requested){await reserve(requested,ref);return requested;}for(let i=0;i<60;i++){const candidate=shortCode(6);try{await reserve(candidate,ref);return candidate}catch(e){if(e.status!==409)throw e}}const e=new Error('Could not create a unique short link. Try again.');e.status=503;throw e;};
  const auth=(doc,plain)=>Boolean(doc&&plain&&doc.tokenHash===sha(plain));
  const smartIntent=prompt=>{const p=text(prompt,1000),l=p.toLowerCase(),url=(p.match(/https?:\/\/[^\s]+/i)||[])[0]||'';if(/pdf editor|edit pdf|merge pdf|watermark/.test(l))return{intent:'pdf',action:'pdf',fields:{}};if(/analytics|scan|click|view|performance/.test(l))return{intent:'analytics',action:'analytics',fields:{}};if(/campaign|utm/.test(l))return{intent:'campaign',action:'campaign',fields:{name:p.replace(/create|campaign|utm/gi,' ').replace(/\s+/g,' ').trim().slice(0,100)}};if(/resume|portfolio|profile|business card|digital card|salon|restaurant|clinic/.test(l)){const name=p.replace(/\b(create|make|build|a|an|the|business|profile|digital|card|for|me|my)\b/gi,' ').replace(/\s+/g,' ').trim().slice(0,100);return{intent:'profile',action:'profile',fields:{name}};}if(/document|brochure|certificate|menu pdf|share pdf/.test(l))return{intent:'document',action:'document',fields:{title:p.slice(0,120)}};if(/link|redirect|short/.test(l)&&url)return{intent:'link',action:'link',fields:{destination:url}};if(/qr|whatsapp|wifi|location|vcard/.test(l)||url)return{intent:'qr',action:'qr',fields:{data:url||p,dynamic:/track|dynamic/.test(l)}};return{intent:'qr',action:'qr',fields:{data:p,dynamic:false}};};
  const chooseLink=(doc,req)=>{if(doc.status!=='active')return{blocked:'This link is paused.'};const t=Date.now();if(doc.startAt&&Date.parse(doc.startAt)>t)return{blocked:'This link is not active yet.'};if(doc.expiresAt&&Date.parse(doc.expiresAt)<=t)return doc.expiredUrl&&validUrl(doc.expiredUrl)?{url:doc.expiredUrl}:{blocked:'This link has expired.'};const info=uaInfo(req.headers['user-agent']),r=doc.routes||{};const dest=info.os==='Android'&&validUrl(r.android)?r.android:info.os==='iOS'&&validUrl(r.ios)?r.ios:info.device==='Desktop'&&validUrl(r.desktop)?r.desktop:doc.destination;return validUrl(dest)?{url:withUtm(dest,doc.utm||{})}:{blocked:'Destination unavailable.'};};

  async function analytics(days,{resourceType='',resourceId=''}={}){
    const normalizedDays=Math.max(1,Math.min(365,Number(days)||30));
    const since=Date.now()-normalizedDays*86400000;const events=[];const extra=await read();
    const wanted=e=>(!resourceType||e.resourceType===resourceType)&&(!resourceId||e.resourceId===resourceId);
    for(const e of Object.values(extra.events||{}))if(!e.isBot&&Date.parse(e.createdAt)>=since&&wanted(e))events.push(e);
    const legacy=await oldDb();
    for(const e of legacy.scans||[]){const x={id:e.id,type:'qr_scan',resourceType:'qrs',resourceId:e.qrId,createdAt:e.createdAt,visitorHash:e.visitorHash,device:e.device,browser:e.browser,os:e.os,referrer:e.referrer||'',isBot:e.isBot};if(!x.isBot&&Date.parse(x.createdAt)>=since&&wanted(x))events.push(x)}
    for(const e of legacy.profileEvents||[]){const x={id:e.id,type:e.type,resourceType:'profiles',resourceId:e.profileId,createdAt:e.createdAt,visitorHash:e.visitorHash,device:e.device,browser:e.browser,os:e.os,referrer:e.referrer||'',action:e.action||e.label||'',isBot:e.isBot};if(!x.isBot&&Date.parse(x.createdAt)>=since&&wanted(x))events.push(x)}
    const counts={qr_scan:0,link_click:0,profile_view:0,document_view:0,document_share:0,action:0},byDay={},devices={},browsers={},systems={},referrers={},unique=new Set();
    const refLabel=v=>{if(!v)return'Direct';try{return new URL(v).hostname.replace(/^www\./,'')||'Direct'}catch{return'Direct'}};
    for(const e of events){counts[e.type]=(counts[e.type]||0)+1;const d=String(e.createdAt||'').slice(0,10);if(d)byDay[d]=(byDay[d]||0)+1;devices[e.device||'Other']=(devices[e.device||'Other']||0)+1;browsers[e.browser||'Other']=(browsers[e.browser||'Other']||0)+1;systems[e.os||'Other']=(systems[e.os||'Other']||0)+1;const ref=refLabel(e.referrer);referrers[ref]=(referrers[ref]||0)+1;if(e.visitorHash)unique.add(e.visitorHash);}
    return{days:normalizedDays,total:events.length,unique:unique.size,counts,byDay,devices,browsers,systems,referrers,recent:events.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,60)};
  }

  async function handle(req,res,url,origin){
    await ready;const p=url.pathname;
    if(p==='/vendor/pdf-lib.min.js'&&req.method==='GET'){
      const vendor=path.join(root,'node_modules','pdf-lib','dist','pdf-lib.min.js');
      if(!fssync.existsSync(vendor)){headers(res,{'Content-Type':'text/javascript; charset=utf-8'});res.writeHead(200);res.end("console.warn('QR AJN PDF editor: run npm install to enable pdf-lib.');");return true;}
      headers(res,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=86400'});res.writeHead(200);fssync.createReadStream(vendor).pipe(res);return true;
    }
    if(p.startsWith('/api/v9/')){
      if(!rate(req,'v9-api',180)){json(res,429,{ok:false,error:'Too many requests. Try again shortly.'});return true;}
      if(req.method==='GET'&&p==='/api/v9/health'){json(res,200,{ok:!isVercel||Boolean(firestore),featurePack:'live-ui-v9',database:firestore?'cloud-firestore':isVercel?'unconfigured':'local-json',persistence:firestore?'durable':isVercel?'not-configured':'local',storage:storageBucket?'firebase-storage':isVercel?'not-configured':'local-files',pdfEditor:true,shortLinks:true,realtimeAnalytics:true});return true;}
      if(req.method==='POST'&&p==='/api/v9/smart/parse'){const b=await readJson(req);json(res,200,{ok:true,...smartIntent(b.prompt)});return true;}
      if(req.method==='POST'&&p==='/api/v9/links'){
        const b=await readJson(req);if(!validUrl(b.destination)){json(res,400,{ok:false,error:'Enter a valid http:// or https:// destination.'});return true;}const linkId=id('lnk'),plain=token(),createdAt=now();const slug=await reserveLinkSlug(b.slug,{type:'links',id:linkId,createdAt});const doc={id:linkId,slug,name:text(b.name||slug,100),destination:b.destination,status:'active',startAt:text(b.startAt,40),expiresAt:text(b.expiresAt,40),expiredUrl:validUrl(b.expiredUrl)?b.expiredUrl:'',routes:{android:validUrl(b.routes?.android)?b.routes.android:'',ios:validUrl(b.routes?.ios)?b.routes.ios:'',desktop:validUrl(b.routes?.desktop)?b.routes.desktop:''},utm:{source:text(b.utm?.source,120),medium:text(b.utm?.medium,120),campaign:text(b.utm?.campaign,120),term:text(b.utm?.term,120),content:text(b.utm?.content,120)},tokenHash:sha(plain),createdAt,updatedAt:createdAt};await mutate(db=>{db.links[linkId]=doc});const o=originSafe(origin);json(res,201,{ok:true,item:{...doc,tokenHash:undefined,publicUrl:`${o}/${slug}`},token:plain,manageUrl:`${o}/manage/v9/links/${linkId}/${plain}`,autoSlug:!text(b.slug,60)});return true;
      }
      if(req.method==='POST'&&p==='/api/v9/campaigns'){
        const b=await readJson(req),cid=id('cmp'),plain=token();const doc={id:cid,name:text(b.name||'Campaign',100),description:text(b.description,500),utm:{source:text(b.utm?.source,120),medium:text(b.utm?.medium,120),campaign:text(b.utm?.campaign||b.name,120)},status:'active',tokenHash:sha(plain),createdAt:now(),updatedAt:now()};await mutate(db=>{db.campaigns[cid]=doc});const o=originSafe(origin);json(res,201,{ok:true,item:{...doc,tokenHash:undefined},token:plain,manageUrl:`${o}/manage/v9/campaigns/${cid}/${plain}`});return true;
      }
      if(req.method==='POST'&&p==='/api/v9/files'){
        const type=text(req.headers['content-type'],100).split(';')[0];if(type!=='application/pdf'){json(res,415,{ok:false,error:'Only PDF files are supported.'});return true;}if(isVercel&&!storageBucket){json(res,503,{ok:false,error:'Firebase Storage is not configured for production PDF publishing.'});return true;}const raw=await body(req,12*1024*1024);if(raw.length<5||raw.subarray(0,5).toString('ascii')!=='%PDF-'){json(res,400,{ok:false,error:'The selected file is not a valid PDF.'});return true;}const fid=id('file'),name=text(url.searchParams.get('name')||'document.pdf',160).replace(/[\/]/g,'-'),storagePath=`v9/uploads/${fid}.pdf`;if(storageBucket)await storageBucket.file(storagePath).save(raw,{resumable:false,metadata:{contentType:'application/pdf',cacheControl:'private,max-age=60'}});else{await fs.mkdir(uploadDir,{recursive:true});await fs.writeFile(path.join(uploadDir,`${fid}.pdf`),raw)}const meta={id:fid,name,type:'application/pdf',size:raw.length,storagePath,createdAt:now()};await mutate(db=>{db.files[fid]=meta});json(res,201,{ok:true,file:meta});return true;
      }
      const fileMatch=p.match(/^\/api\/v9\/files\/([A-Za-z0-9_-]{6,100})$/);
      if(fileMatch&&req.method==='GET'){const db=await read(),meta=db.files[fileMatch[1]];if(!meta){json(res,404,{ok:false,error:'File not found'});return true;}headers(res,{'Content-Type':'application/pdf','Content-Disposition':url.searchParams.get('download')==='1'?`attachment; filename="${meta.name.replace(/"/g,'')}"`:`inline; filename="${meta.name.replace(/"/g,'')}"`,'Cache-Control':'private, max-age=60'});if(storageBucket){const object=storageBucket.file(meta.storagePath||`v9/uploads/${meta.id}.pdf`);try{const [md]=await object.getMetadata();if(md.size)res.setHeader('Content-Length',String(md.size));res.writeHead(200);object.createReadStream().on('error',()=>{try{res.destroy()}catch{}}).pipe(res);return true}catch{json(res,404,{ok:false,error:'File bytes missing'});return true}}const full=path.join(uploadDir,`${meta.id}.pdf`);if(!fssync.existsSync(full)){json(res,404,{ok:false,error:'File bytes missing'});return true;}res.writeHead(200,{'Content-Length':meta.size});fssync.createReadStream(full).pipe(res);return true;}
      if(req.method==='POST'&&p==='/api/v9/documents'){
        const b=await readJson(req),db=await read(),meta=db.files[text(b.fileId,100)];if(!meta){json(res,400,{ok:false,error:'Upload a PDF first.'});return true;}const slug=slugify(b.slug),did=id('doc'),plain=token();await reserve(slug,{type:'documents',id:did,createdAt:now()});const doc={id:did,slug,title:text(b.title||meta.name,120),description:text(b.description,500),fileId:meta.id,status:'active',tokenHash:sha(plain),createdAt:now(),updatedAt:now()};await mutate(d=>{d.documents[did]=doc});const o=originSafe(origin);json(res,201,{ok:true,item:{...doc,tokenHash:undefined,publicUrl:`${o}/${slug}`},token:plain,manageUrl:`${o}/manage/v9/documents/${did}/${plain}`});return true;
      }
      if(req.method==='GET'&&p==='/api/v9/analytics'){json(res,200,{ok:true,...await analytics(url.searchParams.get('days')||30,{resourceType:text(url.searchParams.get('resourceType'),40),resourceId:text(url.searchParams.get('resourceId'),120)})});return true;}
      const linkAnalytics=p.match(/^\/api\/v9\/manage\/links\/([A-Za-z0-9_-]{6,100})\/analytics$/);
      if(linkAnalytics&&req.method==='GET'){const db=await read(),doc=db.links?.[linkAnalytics[1]],plain=text(req.headers['x-management-token']||url.searchParams.get('token'),500);if(!auth(doc,plain)){json(res,403,{ok:false,error:'Invalid private management link.'});return true;}json(res,200,{ok:true,item:{id:doc.id,slug:doc.slug,name:doc.name,status:doc.status},...await analytics(url.searchParams.get('days')||30,{resourceType:'links',resourceId:doc.id})});return true;}
      const manage=p.match(/^\/api\/v9\/manage\/(links|campaigns|documents)\/([A-Za-z0-9_-]{6,100})$/);
      if(manage){const [,kind,key]=manage,db=await read(),doc=db[kind]?.[key],plain=text(req.headers['x-management-token']||url.searchParams.get('token'),500);if(!auth(doc,plain)){json(res,403,{ok:false,error:'Invalid private management link.'});return true;}if(req.method==='GET'){json(res,200,{ok:true,item:{...doc,tokenHash:undefined}});return true;}if(req.method==='PATCH'){const b=await readJson(req),patch={updatedAt:now()};if(kind==='links'){if('name'in b)patch.name=text(b.name||doc.name,100);if('destination'in b){if(!validUrl(b.destination)){json(res,400,{ok:false,error:'Invalid destination.'});return true;}patch.destination=b.destination;}if('status'in b)patch.status=b.status==='paused'?'paused':'active';if('startAt'in b)patch.startAt=text(b.startAt,40);if('expiresAt'in b)patch.expiresAt=text(b.expiresAt,40);if('expiredUrl'in b)patch.expiredUrl=validUrl(b.expiredUrl)?b.expiredUrl:'';if('routes'in b)patch.routes={android:validUrl(b.routes?.android)?b.routes.android:'',ios:validUrl(b.routes?.ios)?b.routes.ios:'',desktop:validUrl(b.routes?.desktop)?b.routes.desktop:''};if('utm'in b)patch.utm={source:text(b.utm?.source,120),medium:text(b.utm?.medium,120),campaign:text(b.utm?.campaign,120),term:text(b.utm?.term,120),content:text(b.utm?.content,120)};}else if(kind==='campaigns'){if('name'in b)patch.name=text(b.name||doc.name,100);if('description'in b)patch.description=text(b.description,500);if('status'in b)patch.status=b.status==='paused'?'paused':'active';if('utm'in b)patch.utm={source:text(b.utm?.source,120),medium:text(b.utm?.medium,120),campaign:text(b.utm?.campaign,120)};}else{if('title'in b)patch.title=text(b.title||doc.title,120);if('description'in b)patch.description=text(b.description,500);if('status'in b)patch.status=b.status==='paused'?'paused':'active';if('fileId'in b){const latest=await read();if(!latest.files[text(b.fileId,100)]){json(res,400,{ok:false,error:'Uploaded PDF not found.'});return true;}patch.fileId=text(b.fileId,100);}}const updated=await mutate(d=>Object.assign(d[kind][key],patch));json(res,200,{ok:true,item:{...updated,tokenHash:undefined}});return true;}if(req.method==='DELETE'){let fileId='';await mutate(d=>{if(doc.slug)delete d.publicLinks[doc.slug];if(kind==='documents')fileId=d.documents[key]?.fileId||'';delete d[kind][key];if(fileId){const stillUsed=Object.values(d.documents).some(x=>x.fileId===fileId);if(!stillUsed)delete d.files[fileId];}});if(kind==='documents'&&fileId&&!Object.values((await read()).files).some(x=>x.id===fileId)){if(storageBucket)await storageBucket.file(`v9/uploads/${fileId}.pdf`).delete({ignoreNotFound:true}).catch(()=>{});else await fs.rm(path.join(uploadDir,`${fileId}.pdf`),{force:true}).catch(()=>{})}json(res,200,{ok:true,deleted:true});return true;}}
      json(res,404,{ok:false,error:'V9 feature API route not found.'});return true;
    }
    if(req.method==='GET'&&/^\/manage\/v9\/(links|campaigns|documents)\/[A-Za-z0-9_-]{6,100}\/[A-Za-z0-9_-]{20,200}$/.test(p))return false;
    if(req.method==='GET'){
      const slug=decodeURIComponent(p.replace(/^\//,'')).replace(/\/$/,'');if(validSlug(slug)){
        const db=await read(),ref=db.publicLinks[slug];if(!ref)return false;
        if(ref.type==='links'){
          const doc=db.links[ref.id];if(!doc){html(res,404,'<h1>Link unavailable</h1>',true);return true;}const chosen=chooseLink(doc,req);if(chosen.blocked){html(res,410,publicMessage(chosen.blocked),true);return true;}await record(req,'link_click','links',doc.id);redirect(res,chosen.url);return true;
        }
        if(ref.type==='documents'){
          const doc=db.documents[ref.id];if(!doc||doc.status!=='active'){html(res,404,publicMessage('Document unavailable'),true);return true;}const meta=db.files[doc.fileId];if(!meta){html(res,404,publicMessage('Document file unavailable'),true);return true;}if(storageBucket){try{const [exists]=await storageBucket.file(meta.storagePath||`v9/uploads/${meta.id}.pdf`).exists();if(!exists){html(res,404,publicMessage('Document file unavailable'),true);return true}}catch{html(res,404,publicMessage('Document file unavailable'),true);return true}}else if(!fssync.existsSync(path.join(uploadDir,`${meta.id}.pdf`))){html(res,404,publicMessage('Document file unavailable'),true);return true;}await record(req,'document_view','documents',doc.id);const o=originSafe(origin);const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>${escape(doc.title)} · QR AJN</title><meta name="description" content="${escape(doc.description||'Shared PDF on QR AJN')}"><link rel="canonical" href="${o}/${escape(doc.slug)}"><style>body{margin:0;font-family:Manrope,Segoe UI,system-ui;background:#eef3fb;color:#111827}.bar{height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 max(18px,calc((100vw - 1180px)/2));background:rgba(255,255,255,.94);border-bottom:1px solid #dce3ee}.brand{font-weight:900}.bar a{background:#5b4cf0;color:white;text-decoration:none;padding:10px 14px;border-radius:11px;font-size:12px;font-weight:800}.frame{width:100%;height:calc(100vh - 69px);border:0}</style></head><body><header class="bar"><div><div class="brand">QR AJN</div><small>${escape(doc.title)}</small></div><a href="/api/v9/files/${escape(meta?.id||'')}?download=1">Download PDF</a></header><iframe class="frame" src="/api/v9/files/${escape(meta?.id||'')}"></iframe></body></html>`;html(res,200,page);return true;
        }
      }
    }
    return false;
  }
  function publicMessage(message){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>QR AJN</title></head><body style="font-family:system-ui;background:#eef3fb;color:#111827"><main style="max-width:620px;margin:90px auto;background:white;border:1px solid #dce3ee;border-radius:20px;padding:28px"><h1>${escape(message)}</h1><p>Powered by QR AJN.</p><a href="/">Go to QR AJN</a></main></body></html>`;}
  return{handle};
}
