import {getAdmin} from "./_admin.js";

const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const attr=esc;
const cleanSlug=s=>String(s||"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,70);
function tel(v){return String(v||"").replace(/[^\d+]/g,"");}
function blockHtml(b){
  if(!b||b.visible===false)return "";
  const title=b.title?`<h2>${esc(b.title)}</h2>`:"",content=typeof b.content==="string"?`<p>${esc(b.content).replace(/\n/g,"<br>")}</p>`:"";
  if(b.type==="video"&&b.url)return `<section class="block">${title}<video controls preload="metadata" src="${attr(b.url)}"></video></section>`;
  if(["map","booking","payment"].includes(b.type)&&b.url)return `<section class="block">${title}${content}<a class="cta secondary" href="${attr(b.url)}" target="_blank" rel="noopener" data-event="${b.type}">${b.type==="booking"?"Book now":b.type==="payment"?"Pay securely":"Open map"}</a></section>`;
  return `<section class="block">${title}${content}${b.url?`<a class="cta secondary" href="${attr(b.url)}" target="_blank" rel="noopener" data-event="website">Open</a>`:""}</section>`;
}
export default async function handler(request,response){
  try{
    const slug=cleanSlug(request.query?.slug||"");if(!slug)return response.status(400).send("Invalid profile.");
    const {db}=getAdmin(),snap=await db.ref(`qrajn/publicBusinessProfiles/${slug}`).get();if(!snap.exists()||snap.val()?.published===false)return response.status(404).send("<h1>Profile not found</h1>");
    const p=snap.val(),blocks=(await db.ref(`qrajn/v6/profileBlocks/${p.ownerId}/${p.id}`).get()).val()||[],canonical=`https://www.qrajn.online/b/${encodeURIComponent(slug)}`,description=String(p.tagline||p.about||`${p.name} on QR AJN`).replace(/\s+/g," ").slice(0,160),image=p.cover||p.logo||"https://www.qrajn.online/assets/qr-ajn-logo.svg";
    const schema={"@context":"https://schema.org","@type":p.type?.toLowerCase().includes("restaurant")?"Restaurant":"LocalBusiness",name:p.name,description,address:p.address||undefined,telephone:p.phone||undefined,url:p.website||canonical,image:[p.logo,p.cover].filter(Boolean)};
    const products=(p.products||[]).slice(0,20).map(x=>`<article class="item">${x.image?`<img src="${attr(x.image)}" alt="">`:""}<div><b>${esc(x.name)}</b>${x.price?`<strong>${esc(x.price)}</strong>`:""}<p>${esc(x.description||"")}</p></div></article>`).join("");
    const services=(p.services||[]).slice(0,20).map(x=>`<article class="item"><div><b>${esc(x.name)}</b>${x.price?`<strong>${esc(x.price)}</strong>`:""}<p>${esc(x.description||"")}</p></div></article>`).join("");
    const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(p.name)} · QR AJN</title><meta name="description" content="${attr(description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${attr(p.name)}"><meta property="og:description" content="${attr(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${attr(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="${attr(p.branding?.accent||"#0f766e")}"><link rel="icon" href="/assets/qr-ajn-logo.svg"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,"\\u003c")}</script><style>
    *{box-sizing:border-box}body{margin:0;background:${esc(p.branding?.background||"#f8fafc")};color:#172033;font:14px/1.55 Inter,system-ui,-apple-system,Segoe UI,sans-serif}.hero{position:relative;min-height:250px;background:linear-gradient(145deg,${esc(p.branding?.accent||"#0f766e")},#0f172a);color:white;padding:30px 18px 70px}.hero:before{content:"";position:absolute;inset:0;background-image:url('${attr(p.cover||"")}');background-size:cover;background-position:center;opacity:${p.cover?.startsWith("http")?".35":"0"}}.hero>*{position:relative;z-index:1}.wrap{width:min(860px,calc(100% - 24px));margin:auto}.brand{display:flex;gap:8px;align-items:center;font-weight:900}.brand img{width:28px;height:28px;background:white;padding:3px;border-radius:8px}.identity{margin-top:45px;display:flex;align-items:end;gap:15px}.logo{width:82px;height:82px;border-radius:20px;background:white;object-fit:cover;border:4px solid rgba(255,255,255,.5)}h1{font-size:30px;margin:0}.tagline{opacity:.82}.content{margin-top:-42px;position:relative;z-index:2;padding-bottom:50px}.card,.block{background:white;border:1px solid #e4ece9;border-radius:18px;padding:18px;margin:12px 0;box-shadow:0 12px 30px rgba(15,118,110,.07)}.actions{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.cta{display:flex;align-items:center;justify-content:center;text-decoration:none;border:0;border-radius:999px;padding:11px 12px;background:${esc(p.branding?.accent||"#0f766e")};color:white;font-weight:800;font-size:12px}.cta.secondary{background:#f0fdfa;color:${esc(p.branding?.accent||"#0f766e")};border:1px solid #bfe9e3}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.item{display:flex;gap:10px;border:1px solid #edf2f0;border-radius:14px;padding:10px}.item img{width:76px;height:76px;object-fit:cover;border-radius:10px}.item b,.item strong{display:block}.item strong{color:${esc(p.branding?.accent||"#0f766e")};margin-top:3px}.item p{font-size:12px;color:#64748b;margin:4px 0}.block video{width:100%;border-radius:12px}.lead input,.lead textarea{width:100%;border:1px solid #dce5e2;border-radius:11px;padding:11px;margin:6px 0}.lead label{font-size:11px}.consent{display:flex;gap:8px;align-items:flex-start;margin:10px 0;color:#64748b;font-size:10px}.consent input{width:auto;margin:2px 0}.footer{text-align:center;color:#64748b;font-size:10px;padding:25px}.footer a{color:${esc(p.branding?.accent||"#0f766e")}}@media(max-width:650px){.actions,.grid{grid-template-columns:1fr 1fr}.identity{align-items:center}.logo{width:68px;height:68px}h1{font-size:24px}}
    </style></head><body><header class="hero"><div class="wrap"><div class="brand"><img src="/assets/qr-ajn-logo.svg" alt="">QR AJN</div><div class="identity">${p.logo?`<img class="logo" src="${attr(p.logo)}" alt="${attr(p.name)} logo">`:""}<div><h1>${esc(p.name)}</h1><div class="tagline">${esc(p.tagline||p.type||"")}</div></div></div></div></header><main class="wrap content"><section class="card"><div class="actions">${p.phone?`<a class="cta" href="tel:${tel(p.phone)}" data-event="call">Call</a>`:""}${p.whatsapp?`<a class="cta" href="https://wa.me/${tel(p.whatsapp)}?text=${encodeURIComponent(p.whatsappMessage||"Hi")}" target="_blank" rel="noopener" data-event="whatsapp">WhatsApp</a>`:""}${p.mapsUrl?`<a class="cta secondary" href="${attr(p.mapsUrl)}" target="_blank" rel="noopener" data-event="directions">Directions</a>`:""}${p.website?`<a class="cta secondary" href="${attr(p.website)}" target="_blank" rel="noopener" data-event="website">Website</a>`:""}</div>${p.about?`<h2>About</h2><p>${esc(p.about).replace(/\n/g,"<br>")}</p>`:""}${p.address?`<p><b>Address:</b> ${esc(p.address)}</p>`:""}${p.hours?`<p><b>Hours:</b> ${esc(p.hours)}</p>`:""}</section>${products?`<section class="card"><h2>Products</h2><div class="grid">${products}</div></section>`:""}${services?`<section class="card"><h2>Services</h2><div class="grid">${services}</div></section>`:""}${blocks.map(blockHtml).join("")}${p.leadCapture?.enabled!==false?`<section class="card lead"><h2>${esc(p.leadCapture?.title||"Send an enquiry")}</h2><form id="lead"><input name="name" placeholder="Your name" required><input name="phone" placeholder="Phone" required>${p.leadCapture?.askEmail?`<input name="email" type="email" placeholder="Email">`:""}${p.leadCapture?.askMessage!==false?`<textarea name="message" rows="3" placeholder="Message"></textarea>`:""}<label class="consent"><input type="checkbox" name="consent" required> I agree to share these details with this profile owner so they can respond to my enquiry.</label><button class="cta" type="submit">Send enquiry</button><p id="lead-status"></p></form></section>`:""}</main><footer class="footer">${p.branding?.whiteLabel?"":`Powered by <a href="https://www.qrajn.online/">QR AJN</a>`}</footer><script>
    const slug=${JSON.stringify(slug)};
    function track(eventType,source=""){navigator.sendBeacon?.("/api/v1/profile-event",new Blob([JSON.stringify({slug,eventType,source})],{type:"application/json"}))||fetch("/api/v1/profile-event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,eventType,source}),keepalive:true}).catch(()=>{});}
    track("view","ssr");
    document.querySelectorAll("[data-event]").forEach(a=>a.addEventListener("click",()=>track(a.dataset.event,"cta")));
    document.querySelector("#lead")?.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),status=document.querySelector("#lead-status");status.textContent="Sending…";const body={slug,name:f.get("name"),phone:f.get("phone"),email:f.get("email")||"",message:f.get("message")||"",consent:f.get("consent")==="on"};try{const r=await fetch("/api/v1/profile-lead",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not send enquiry.");status.textContent="Thank you. Your enquiry was sent.";e.currentTarget.reset();}catch(err){status.textContent=err.message;}});
    </script></body></html>`;
    response.status(200).setHeader("content-type","text/html; charset=utf-8").setHeader("cache-control","public, s-maxage=60, stale-while-revalidate=300").setHeader("x-content-type-options","nosniff").send(html);
  }catch(error){response.status(error?.code==="SERVER_NOT_CONFIGURED"?503:500).send("<h1>Profile temporarily unavailable</h1>");}
}
